
input(policy_password(policy(3-5, f), fgfff)).
input(policy_password(policy(6-20, n), qlzsnnnndwnlhwnxhvjn)).
input(policy_password(policy(6-7, j), jjjjjwrj)).
input(policy_password(policy(8-10, g), gggggggggg)).
input(policy_password(policy(5-6, t), ttttttft)).
input(policy_password(policy(6-11, h), khmchszhmzm)).
input(policy_password(policy(4-6, q), qqbjqqqj)).
input(policy_password(policy(6-8, j), gtkwwjjj)).
input(policy_password(policy(13-14, w), lwgwrwczwwhkww)).
input(policy_password(policy(2-4, p), vcnptzdppvpdzp)).
input(policy_password(policy(4-6, n), pmlnzwrnbnxnpmwmhbnz)).
input(policy_password(policy(4-9, w), wwprdwwwx)).
input(policy_password(policy(13-20, b), rbbcbbbbbbbbsbbbbbmj)).
input(policy_password(policy(1-3, r), zwhrnvr)).
input(policy_password(policy(4-6, f), fmfgfcf)).
input(policy_password(policy(13-15, z), zxzzzzzzzzvxkplvzzz)).
input(policy_password(policy(12-18, r), phjqccgmgzmdwxgtrtb)).
input(policy_password(policy(5-19, s), ssssssssssssssssssss)).
input(policy_password(policy(6-7, d), pddqmdd)).
input(policy_password(policy(7-9, p), pwrlpvlhpfpppzp)).
input(policy_password(policy(4-5, m), mpmmmm)).
input(policy_password(policy(9-10, s), ssxsssssrj)).
input(policy_password(policy(6-9, p), lpjrvpppp)).
input(policy_password(policy(6-13, r), rrrzvtrgrhqxqrvrvwzr)).
input(policy_password(policy(1-3, p), dpjp)).
input(policy_password(policy(6-7, w), wkjnmww)).
input(policy_password(policy(1-5, r), cfqhhr)).
input(policy_password(policy(5-9, m), wmmlpgmqmmrm)).
input(policy_password(policy(12-13, x), sxgnwxxkjwrxr)).
input(policy_password(policy(6-8, n), lnnrnnnnn)).
input(policy_password(policy(10-11, q), kqqqzqqfqqqqq)).
input(policy_password(policy(12-17, k), kkkkkkkkkkpkkhgvnjhk)).
input(policy_password(policy(12-13, v), vvvvvvvvvvvvvv)).
input(policy_password(policy(12-15, h), hhhhhhhjkhhhhhth)).
input(policy_password(policy(6-7, l), hmqtlllnllnlmtqnn)).
input(policy_password(policy(6-9, m), mcmmmdnmh)).
input(policy_password(policy(3-5, k), kkhtn)).
input(policy_password(policy(2-4, n), tnfjmnnn)).
input(policy_password(policy(5-6, j), cjwlmn)).
input(policy_password(policy(4-11, b), bcbbkrlgcbbc)).
input(policy_password(policy(5-10, r), rcrcgrrrzwrrxgpzwrcm)).
input(policy_password(policy(3-4, n), znnn)).
input(policy_password(policy(11-14, s), sssjsssssssssss)).
input(policy_password(policy(6-7, d), rwdddddmdddddkdd)).
input(policy_password(policy(1-4, s), gssssskssss)).
input(policy_password(policy(4-5, j), jjjjzj)).
input(policy_password(policy(11-12, j), cjjjgpjxnjjk)).
input(policy_password(policy(3-6, z), zzkdzzz)).
input(policy_password(policy(7-9, d), mkddddqdhddgdd)).
input(policy_password(policy(1-9, d), rxwqcdrswdg)).
input(policy_password(policy(2-4, m), gmmmn)).
input(policy_password(policy(2-4, k), kkkmk)).
input(policy_password(policy(15-16, r), rrrrrrrrlrrrrrrr)).
input(policy_password(policy(1-11, g), grgggcgggcggp)).
input(policy_password(policy(7-8, q), qqqjqqgq)).
input(policy_password(policy(13-14, c), cxccccgccvcpccccc)).
input(policy_password(policy(2-5, j), txvwlls)).
input(policy_password(policy(3-13, w), plwqwhbwdgxcwfmwjl)).
input(policy_password(policy(9-11, g), ggggggggggggggggdgg)).
input(policy_password(policy(3-12, g), ggsggggggpgm)).
input(policy_password(policy(3-11, g), bcgqgxmbjpwm)).
input(policy_password(policy(8-9, z), zxvzrzzzzzdvzzgz)).
input(policy_password(policy(17-18, z), zzzxzzzzzzzzzzzzsw)).
input(policy_password(policy(9-10, t), ftrmtttktttttdtmdk)).
input(policy_password(policy(15-17, r), rjrrprrrrrrrrrrfrrrr)).
input(policy_password(policy(7-8, k), kkkkkkkkk)).
input(policy_password(policy(6-13, n), nnnvnfgntnnnjnnxh)).
input(policy_password(policy(17-19, l), llllflllllllllllqlrl)).
input(policy_password(policy(11-13, d), hdlddddddhxddddkd)).
input(policy_password(policy(13-17, h), hhhhhhhhhhhhnhhhjhhh)).
input(policy_password(policy(1-12, c), ncccczwcnctcwcc)).
input(policy_password(policy(4-5, w), wgwkl)).
input(policy_password(policy(12-13, w), wwwwwwwwwwwwfwww)).
input(policy_password(policy(3-12, s), scssgwshsspsss)).
input(policy_password(policy(15-17, w), wwwwwcwxmhwwwwwwwww)).
input(policy_password(policy(1-3, x), xxxxw)).
input(policy_password(policy(8-9, p), mpppppppzptp)).
input(policy_password(policy(11-12, n), nntnbnnnnnmx)).
input(policy_password(policy(2-10, x), xrspbmkcthqsdxrdxwx)).
input(policy_password(policy(13-14, l), lllllllpllllll)).
input(policy_password(policy(5-10, x), xxxxjxjdrx)).
input(policy_password(policy(7-8, k), kkkkkkjk)).
input(policy_password(policy(9-11, k), vkkkkkkvkkzddbzr)).
input(policy_password(policy(3-8, r), lbrrcwbdf)).
input(policy_password(policy(6-14, l), lgwllrgllllllgllll)).
input(policy_password(policy(6-9, q), nqqkhqqtqgqc)).
input(policy_password(policy(2-4, g), ggxggggggg)).
input(policy_password(policy(12-13, k), kkkkkjkkkkkvf)).
input(policy_password(policy(5-9, b), scvbbpzbbbzbfb)).
input(policy_password(policy(16-17, d), mdddddddddddddcttd)).
input(policy_password(policy(4-10, l), lllflllllllllllllll)).
input(policy_password(policy(3-6, q), qqqqqtqqqq)).
input(policy_password(policy(1-3, n), pblsghl)).
input(policy_password(policy(9-11, v), bvvvmvfvvgtvfpv)).
input(policy_password(policy(4-5, s), ssshq)).
input(policy_password(policy(5-8, g), ggwgnggp)).
input(policy_password(policy(1-4, f), ffmr)).
input(policy_password(policy(4-5, g), ggwzs)).
input(policy_password(policy(4-5, h), fhhqs)).
input(policy_password(policy(10-17, l), clhlllhslxpgljpvlrkl)).
input(policy_password(policy(7-9, m), pnswhtmvmsrmjwrbfz)).
input(policy_password(policy(6-16, v), vvvvqcvvvdzvjvldvv)).
input(policy_password(policy(5-6, c), cntcrl)).
input(policy_password(policy(12-13, n), nnnnnnnnnnnnln)).
input(policy_password(policy(2-4, w), wwww)).
input(policy_password(policy(2-13, w), swrqssmmwrxtw)).
input(policy_password(policy(15-16, z), zzzzzzzzzzzzzzgqzzz)).
input(policy_password(policy(6-8, c), cctvkbdcwcbvhc)).
input(policy_password(policy(1-2, w), wwzdwjtm)).
input(policy_password(policy(1-3, z), mzzh)).
input(policy_password(policy(6-13, t), fttttdwtttttkht)).
input(policy_password(policy(3-9, g), cggfjgqngwmj)).
input(policy_password(policy(1-5, k), pkkkkkkrk)).
input(policy_password(policy(1-5, q), qknqd)).
input(policy_password(policy(7-11, t), tttttckttkb)).
input(policy_password(policy(6-7, q), qqqqqbl)).
input(policy_password(policy(16-17, c), ccccccccccccccctc)).
input(policy_password(policy(2-5, v), vfcnvlvvvxvrnvvvvvv)).
input(policy_password(policy(1-5, w), nwtwnnwwhtwwdwwww)).
input(policy_password(policy(2-10, v), ftvxxbjzlqctp)).
input(policy_password(policy(5-7, d), nddddgddjdbk)).
input(policy_password(policy(8-11, s), wxqjwkcsflssm)).
input(policy_password(policy(17-20, v), vvvvvvvvpvgvvvvvvvvv)).
input(policy_password(policy(6-8, w), wwlwwwqfw)).
input(policy_password(policy(13-14, r), rrrrgrrrrrrrrr)).
input(policy_password(policy(5-6, t), ttttzq)).
input(policy_password(policy(13-14, c), cccccccccccccc)).
input(policy_password(policy(11-12, k), kwzkkkbdkjkk)).
input(policy_password(policy(10-11, t), ttttpttttrwwtttt)).
input(policy_password(policy(3-4, w), ljwwww)).
input(policy_password(policy(7-8, q), ggqzdvqqw)).
input(policy_password(policy(1-3, z), zzsg)).
input(policy_password(policy(1-2, c), crjvdhgwckszmzpcjmr)).
input(policy_password(policy(10-11, n), nngnntnnnqn)).
input(policy_password(policy(7-16, w), bwdgwwwgwwnnqtcwc)).
input(policy_password(policy(4-16, v), vfkvqvvsvnjhfvvv)).
input(policy_password(policy(10-11, p), fgbhpzqvkmn)).
input(policy_password(policy(10-11, w), wswgwqwszwwhwnwww)).
input(policy_password(policy(15-16, t), stwtfxttthptttttt)).
input(policy_password(policy(1-3, v), vlvsdmrv)).
input(policy_password(policy(5-8, z), zzzzfzzz)).
input(policy_password(policy(14-15, t), ttpvtrlqtlcdrlv)).
input(policy_password(policy(2-6, b), qwfnbkc)).
input(policy_password(policy(6-9, p), jppjpspplm)).
input(policy_password(policy(3-4, s), brgqssz)).
input(policy_password(policy(2-6, q), cqwqlq)).
input(policy_password(policy(13-14, d), rrdljqdddddcxzdc)).
input(policy_password(policy(8-13, s), tsnssssssssrcssrssq)).
input(policy_password(policy(7-8, d), dwddddgl)).
input(policy_password(policy(9-15, b), gspmhlgbbzbbbrbt)).
input(policy_password(policy(3-4, h), khhh)).
input(policy_password(policy(3-4, c), nkccpmcct)).
input(policy_password(policy(6-7, g), ggggggg)).
input(policy_password(policy(17-18, p), ppppppppppppppppjnp)).
input(policy_password(policy(2-6, f), rfjxtff)).
input(policy_password(policy(3-4, g), ggvg)).
input(policy_password(policy(7-9, k), kkkkkkkkkkk)).
input(policy_password(policy(11-16, f), fjdffrtfffjfdffcln)).
input(policy_password(policy(4-8, w), lhpdwbnfssswwfswwwrw)).
input(policy_password(policy(5-9, l), lvlllflll)).
input(policy_password(policy(5-6, t), wtrtlr)).
input(policy_password(policy(4-8, m), mnmmjgqtgs)).
input(policy_password(policy(5-11, n), nnrngbnntnk)).
input(policy_password(policy(5-8, s), ssssfssss)).
input(policy_password(policy(7-14, m), hrnbhsfcvdmxbmvzfvnq)).
input(policy_password(policy(1-5, x), xxxxxxxxwxxdg)).
input(policy_password(policy(1-10, v), vcjvvjvvvv)).
input(policy_password(policy(5-10, l), vvdmhskmprszklvvl)).
input(policy_password(policy(3-17, d), dsddkddddddqddddfjdd)).
input(policy_password(policy(9-13, p), pppppppptpppqp)).
input(policy_password(policy(12-13, h), hhhhhhhhhhjhh)).
input(policy_password(policy(1-4, z), mrvlzlzhzlp)).
input(policy_password(policy(3-4, h), hhmc)).
input(policy_password(policy(7-17, w), wwwwwwwwwwwwwwwwww)).
input(policy_password(policy(6-8, z), cgzxzznzzdhcvwh)).
input(policy_password(policy(4-5, g), mgggg)).
input(policy_password(policy(7-8, t), ttrthtdkjtgtts)).
input(policy_password(policy(8-9, w), wwwwwwwpw)).
input(policy_password(policy(9-15, k), kkkkkkkkkkkkkkk)).
input(policy_password(policy(8-14, q), qqqqqqqqnqqqqq)).
input(policy_password(policy(14-19, w), jkwbwwlwdcmwmmwwrwr)).
input(policy_password(policy(4-5, m), hsxgkdmz)).
input(policy_password(policy(2-4, v), vsvqvcv)).
input(policy_password(policy(4-9, h), grhnhhmhhxhlh)).
input(policy_password(policy(6-14, t), tmttrjbtjtfttc)).
input(policy_password(policy(1-4, d), pjdbrb)).
input(policy_password(policy(15-16, r), rrrrrblrrrrrrrxwr)).
input(policy_password(policy(16-18, p), pppjpppppptpplpppppp)).
input(policy_password(policy(4-7, x), mxtngxnpsx)).
input(policy_password(policy(9-10, b), bbbdbqvmrgbzbbbb)).
input(policy_password(policy(4-5, w), wwwwj)).
input(policy_password(policy(1-2, d), dgws)).
input(policy_password(policy(3-10, l), lglsphlbgfmgdtw)).
input(policy_password(policy(10-11, h), hhhhhfhhhpdhh)).
input(policy_password(policy(5-9, x), xxxxqgxxjf)).
input(policy_password(policy(11-19, m), bfmxmmfgzzhqwsmgwmlr)).
input(policy_password(policy(10-14, x), xxxrxkxxqrlxmpxbdx)).
input(policy_password(policy(3-8, l), lxlxvwlllznlptfv)).
input(policy_password(policy(5-9, h), hhthhhhshdq)).
input(policy_password(policy(1-5, q), sqqqqqqq)).
input(policy_password(policy(9-14, j), jxfcjpjfjjgjjjjjjjhj)).
input(policy_password(policy(1-7, g), gvdgjgsvvgnd)).
input(policy_password(policy(2-5, t), tmttpttttt)).
input(policy_password(policy(17-19, c), ccccclcccccccccccccc)).
input(policy_password(policy(10-13, d), mdvddtsddrxtx)).
input(policy_password(policy(11-12, g), gggggggwggzgp)).
input(policy_password(policy(3-5, k), hzxnpkq)).
input(policy_password(policy(9-11, q), qqqqqsqqqqq)).
input(policy_password(policy(8-9, x), btrkbxngx)).
input(policy_password(policy(3-5, g), jpkchcxcxhzfhsggqkg)).
input(policy_password(policy(7-13, s), ssssssssscssssn)).
input(policy_password(policy(13-15, p), pppppppnppppppp)).
input(policy_password(policy(5-15, f), ffffjfffffffffgf)).
input(policy_password(policy(2-4, p), zqphp)).
input(policy_password(policy(1-4, r), wrrr)).
input(policy_password(policy(3-9, b), jsjcbrkkczkzmjbg)).
input(policy_password(policy(1-2, k), kkkkl)).
input(policy_password(policy(2-3, n), dlnxjwzstsdxns)).
input(policy_password(policy(7-14, v), fvvvvzhhvpsvvckdvv)).
input(policy_password(policy(2-8, r), rrrrwrhrrrr)).
input(policy_password(policy(5-8, n), nnxdnnnnnn)).
input(policy_password(policy(5-12, c), scmcdscccccmcc)).
input(policy_password(policy(9-10, v), vvvvvvvvjm)).
input(policy_password(policy(14-15, w), lwppdwwwwdmrrww)).
input(policy_password(policy(6-7, c), qcgcvxdrcccpxchrnlq)).
input(policy_password(policy(8-10, x), hbrqsksxwxxttz)).
input(policy_password(policy(18-19, w), jnftgwpwmwfdgrcpkww)).
input(policy_password(policy(3-4, k), ffkj)).
input(policy_password(policy(5-9, f), flffsvffsff)).
input(policy_password(policy(3-4, k), kkkkk)).
input(policy_password(policy(1-3, l), dlglkll)).
input(policy_password(policy(10-16, f), bfffjzfffnfffffxhfff)).
input(policy_password(policy(11-20, d), ddbdqsddddddddddfddd)).
input(policy_password(policy(6-20, l), vmjltmkclbmqrflzgdzl)).
input(policy_password(policy(5-19, f), ffffffffffffffffffff)).
input(policy_password(policy(5-10, n), nnnnmnnfnz)).
input(policy_password(policy(4-13, f), kmrfrfkvjxdbftvhnsdm)).
input(policy_password(policy(10-11, k), kkkkkkkkskk)).
input(policy_password(policy(12-13, k), kkkkkkkkkkkhj)).
input(policy_password(policy(7-8, p), ppppppnhw)).
input(policy_password(policy(5-8, l), gtpllwklh)).
input(policy_password(policy(13-14, h), hhhhhhhhzhhwsrh)).
input(policy_password(policy(7-15, h), hhhhhhthhhhhthqgfh)).
input(policy_password(policy(1-3, f), mfdmhv)).
input(policy_password(policy(15-16, f), fffffflfffffffbqf)).
input(policy_password(policy(12-13, c), cccmcccccccxn)).
input(policy_password(policy(2-12, q), nqltxqfdcrxqvt)).
input(policy_password(policy(8-10, d), dddddddddvdddd)).
input(policy_password(policy(2-9, g), mdrwnvtsd)).
input(policy_password(policy(12-13, l), lllllllllllll)).
input(policy_password(policy(2-3, m), mnrgmdm)).
input(policy_password(policy(6-9, v), hvvvvvvvv)).
input(policy_password(policy(4-7, q), bqqqrqcqqqq)).
input(policy_password(policy(8-11, v), vvvvdvvvvvr)).
input(policy_password(policy(3-4, n), cnnw)).
input(policy_password(policy(2-12, r), rrrklfrrrksrr)).
input(policy_password(policy(2-12, p), pxppklhsppwdxwcpzvm)).
input(policy_password(policy(10-11, n), nnnnnnnnnnn)).
input(policy_password(policy(5-6, w), wfwwww)).
input(policy_password(policy(3-5, p), pppppp)).
input(policy_password(policy(3-8, g), ggggggggggggggg)).
input(policy_password(policy(1-4, x), xxxxx)).
input(policy_password(policy(11-16, d), ngcdkglddtppbddgdrd)).
input(policy_password(policy(11-12, k), kkkkkkkkkkhr)).
input(policy_password(policy(12-13, c), hgxxchcvxpdlsrt)).
input(policy_password(policy(1-3, m), vmmm)).
input(policy_password(policy(4-6, z), kvzgzzzp)).
input(policy_password(policy(11-12, d), dzddzlcbvdxk)).
input(policy_password(policy(10-11, g), ggsgggggggggdz)).
input(policy_password(policy(6-8, q), xfhgpqltbfbdzqg)).
input(policy_password(policy(4-7, v), vvvlvcxmvvxq)).
input(policy_password(policy(5-7, v), vkkgvgvnpvvlpgkv)).
input(policy_password(policy(6-7, b), bbkvnwbqblbvbb)).
input(policy_password(policy(2-4, l), wmll)).
input(policy_password(policy(6-9, j), djqjcxxljm)).
input(policy_password(policy(3-4, j), nmzcsnlnjjjdms)).
input(policy_password(policy(3-8, w), wnwwsvww)).
input(policy_password(policy(9-20, m), wbntxzztwmblxmsmltmg)).
input(policy_password(policy(7-8, r), rprrrtrf)).
input(policy_password(policy(1-3, r), lnrfxfswmhgvf)).
input(policy_password(policy(5-12, k), zlkdlktsrqjt)).
input(policy_password(policy(13-14, v), vvvvvvvvvvvvvbv)).
input(policy_password(policy(11-12, d), ddddddddddgc)).
input(policy_password(policy(9-11, c), mdwpjjcdcrc)).
input(policy_password(policy(5-6, m), mmmmnl)).
input(policy_password(policy(5-6, l), lblldn)).
input(policy_password(policy(13-14, c), sccfcxsnsclccc)).
input(policy_password(policy(4-5, q), qqkkq)).
input(policy_password(policy(5-8, m), mmmmmmmm)).
input(policy_password(policy(5-8, z), tzhzzttzvwfcv)).
input(policy_password(policy(12-15, b), bbbbbbbbbbbtdfb)).
input(policy_password(policy(7-10, b), bbnplbbxxbh)).
input(policy_password(policy(1-7, x), zxxxxxvx)).
input(policy_password(policy(6-17, b), kbnbbbbbptbbrbbbb)).
input(policy_password(policy(1-3, l), llllll)).
input(policy_password(policy(13-15, c), ccccccccccccqcz)).
input(policy_password(policy(1-8, s), sssssssb)).
input(policy_password(policy(12-19, x), xxxxxxxxpxxcxxxxxxq)).
input(policy_password(policy(12-13, x), xxxxxxxxxxxxxx)).
input(policy_password(policy(14-18, w), wwwwwwwwwwwwwlwmbk)).
input(policy_password(policy(7-8, q), mzwqblqqz)).
input(policy_password(policy(1-7, p), hrppppgdzp)).
input(policy_password(policy(2-7, n), qmvpmsjncgkgpbb)).
input(policy_password(policy(8-10, x), xxxxxxxwxx)).
input(policy_password(policy(2-4, v), rfcpmpvsswsrjkxpdrxh)).
input(policy_password(policy(14-16, k), kkkkkkkkkkkhkkskkt)).
input(policy_password(policy(14-15, d), ddddddkdddddrqdd)).
input(policy_password(policy(4-16, m), njmqmmmjfmmxhmwgdbc)).
input(policy_password(policy(12-13, h), hdmdfhhhzhkdhr)).
input(policy_password(policy(3-14, n), nbntrsmnmrcwbf)).
input(policy_password(policy(6-8, h), hhwhhlhnhh)).
input(policy_password(policy(18-19, v), vvvvvvvvvvvvjvvvvvp)).
input(policy_password(policy(11-20, l), ldllllbvllmqllmlllfl)).
input(policy_password(policy(2-3, d), dcddd)).
input(policy_password(policy(4-6, n), bsnncn)).
input(policy_password(policy(3-6, f), dwlfqfzgs)).
input(policy_password(policy(8-12, d), xdddddfhnddfddd)).
input(policy_password(policy(5-13, l), llllqlllllmllll)).
input(policy_password(policy(10-14, m), mnmzrmmmmwmmqm)).
input(policy_password(policy(3-12, c), qjchcclnbccccpc)).
input(policy_password(policy(7-16, j), jjjjjjwjjjjjjrjnjj)).
input(policy_password(policy(1-10, v), svvdvvgmgpkfkvhvv)).
input(policy_password(policy(2-4, b), gbpbczblbbv)).
input(policy_password(policy(7-9, w), drwwbwtgwswwww)).
input(policy_password(policy(2-8, h), fhkprhplz)).
input(policy_password(policy(1-6, m), mmmmwm)).
input(policy_password(policy(3-4, g), gggp)).
input(policy_password(policy(1-3, q), qqqqj)).
input(policy_password(policy(10-11, h), htfrdwrnkzntnfpdmkhq)).
input(policy_password(policy(5-6, x), nxxxxxxxj)).
input(policy_password(policy(7-8, w), wwwcwwww)).
input(policy_password(policy(1-5, h), lhhhhh)).
input(policy_password(policy(7-8, f), ffjfftff)).
input(policy_password(policy(3-5, g), kdgfgjgbghggp)).
input(policy_password(policy(2-11, p), flgpvfbhpzxmmntw)).
input(policy_password(policy(12-13, z), zzzzzzhzzzzgzzqz)).
input(policy_password(policy(12-13, j), ttmhmdfjpdpnj)).
input(policy_password(policy(5-7, h), hhhhvhh)).
input(policy_password(policy(9-13, x), xhxbxxsxxqwxxvxxxx)).
input(policy_password(policy(1-3, c), ccchcc)).
input(policy_password(policy(2-5, h), hhrsh)).
input(policy_password(policy(1-3, q), rqqq)).
input(policy_password(policy(2-8, x), sxrxbcxx)).
input(policy_password(policy(12-15, b), bbbbnbbrbcbtbbb)).
input(policy_password(policy(14-18, m), hmmmmmmmkmmmmmmmmrmm)).
input(policy_password(policy(1-4, v), vvvv)).
input(policy_password(policy(5-11, h), brnzvqhrrwh)).
input(policy_password(policy(4-10, f), dbtfdvlfnffqmwp)).
input(policy_password(policy(3-16, r), krrrvmrwrrrtrrrrkrwr)).
input(policy_password(policy(11-15, c), gxbccccccccccbh)).
input(policy_password(policy(13-18, z), zzrzzzzzzzzzzzzzzzz)).
input(policy_password(policy(1-3, l), lkvxtrthfvmdzn)).
input(policy_password(policy(7-9, p), vpppmpppppp)).
input(policy_password(policy(3-4, w), wwwwwwww)).
input(policy_password(policy(8-11, z), vlzzzlzvzzmzzz)).
input(policy_password(policy(2-4, v), vqfv)).
input(policy_password(policy(10-11, s), sssssslssgss)).
input(policy_password(policy(4-5, z), zzzww)).
input(policy_password(policy(11-19, p), zpbpdjfjpdfgnpphhpg)).
input(policy_password(policy(1-8, f), fftlxmfl)).
input(policy_password(policy(9-10, p), phlpqzppxpxp)).
input(policy_password(policy(5-7, q), kbqjqqq)).
input(policy_password(policy(3-6, m), jcblmv)).
input(policy_password(policy(9-10, l), llllllllll)).
input(policy_password(policy(13-14, w), wbwhwwwwhwqwmswwmjwf)).
input(policy_password(policy(6-11, j), jjjjvtjwjbdjj)).
input(policy_password(policy(4-8, j), jljjjvgj)).
input(policy_password(policy(3-4, r), lrhvrzrr)).
input(policy_password(policy(2-4, p), plpfkphpq)).
input(policy_password(policy(2-6, b), bbbbrbvwbbgh)).
input(policy_password(policy(2-11, t), mmjmcwcdcbtztxfbtst)).
input(policy_password(policy(7-15, r), grsrrjrrtrgvrtrrr)).
input(policy_password(policy(6-17, d), dddddgddpddzddddddd)).
input(policy_password(policy(3-10, t), qpnbrnmmjtjxtdg)).
input(policy_password(policy(6-7, v), vvvvvhb)).
input(policy_password(policy(5-20, j), vxmkjnssjdtldsdwltlg)).
input(policy_password(policy(7-10, r), rrrrrrrrrrr)).
input(policy_password(policy(2-4, r), rrpl)).
input(policy_password(policy(3-4, m), mmzg)).
input(policy_password(policy(1-8, h), fshhjrhm)).
input(policy_password(policy(5-8, m), mmmvmmvmmnmdxnjcjpn)).
input(policy_password(policy(8-10, m), mmmmmmmlmzmm)).
input(policy_password(policy(14-15, q), qqqqqqqqqqqqqqb)).
input(policy_password(policy(6-16, q), qhkdtqnzqqqjgjrqrkbq)).
input(policy_password(policy(3-9, b), gtbbfgfhbs)).
input(policy_password(policy(14-16, h), hhhhdhhhmhhhhmhhh)).
input(policy_password(policy(9-10, n), nnnndnnnvjnl)).
input(policy_password(policy(11-12, p), pqpppppppppppp)).
input(policy_password(policy(7-9, d), ddpwfdtdd)).
input(policy_password(policy(6-10, z), qzzzzjzzmz)).
input(policy_password(policy(9-14, q), qqdjqdqqrqqwqnqqp)).
input(policy_password(policy(6-7, k), kkkkkbkk)).
input(policy_password(policy(7-14, j), hjvjmzkhgltffljjvjj)).
input(policy_password(policy(4-5, z), znhzz)).
input(policy_password(policy(11-16, r), rrrrbxdrrqrrsrrb)).
input(policy_password(policy(5-8, v), vvhvvvvvwvlvhlqg)).
input(policy_password(policy(4-10, n), wvnnjnndcnk)).
input(policy_password(policy(5-6, g), ggkggk)).
input(policy_password(policy(8-9, w), wwwwwwwww)).
input(policy_password(policy(5-9, r), mrwrrrrrx)).
input(policy_password(policy(4-6, r), jcfrjrrrg)).
input(policy_password(policy(6-9, w), wkwwsxwgfcwqb)).
input(policy_password(policy(5-6, x), grxjxnrb)).
input(policy_password(policy(2-7, s), nsmldnsszdk)).
input(policy_password(policy(5-9, j), gjjzkjvjwjcjbj)).
input(policy_password(policy(6-11, r), jtrgcvwccrrrfmj)).
input(policy_password(policy(7-12, j), jfjjmjjjjxjqzdjjxq)).
input(policy_password(policy(1-2, n), nnwqcnr)).
input(policy_password(policy(5-16, l), lllpclllllllblllll)).
input(policy_password(policy(5-6, j), wjgdjcdpjxfjxnjj)).
input(policy_password(policy(3-16, s), klstwqksfclmcbbcn)).
input(policy_password(policy(17-18, t), ttttdtttttthtttttttt)).
input(policy_password(policy(9-13, p), ppppppvpvhhqp)).
input(policy_password(policy(1-2, n), tsnnn)).
input(policy_password(policy(3-4, p), jpqpjmpplpw)).
input(policy_password(policy(4-6, t), dtfthsxtfpd)).
input(policy_password(policy(2-6, m), zhszctkm)).
input(policy_password(policy(1-13, p), dppmkpbprgppxcpvhrpz)).
input(policy_password(policy(2-7, m), gvmmflp)).
input(policy_password(policy(9-16, c), rcdsppjbcwdxnfbc)).
input(policy_password(policy(5-15, p), pppxpppqnhpptpppz)).
input(policy_password(policy(10-13, q), xfhqhkqkjqjwqqcfrgl)).
input(policy_password(policy(14-15, t), tttttttttttttdvtttt)).
input(policy_password(policy(5-8, q), qqqbqvqzqqn)).
input(policy_password(policy(1-7, v), cvgvvbcgjv)).
input(policy_password(policy(6-9, r), rrrrrrrdr)).
input(policy_password(policy(2-11, j), wjjgxngswkj)).
input(policy_password(policy(11-13, d), dddddddddddddm)).
input(policy_password(policy(5-8, p), pzppppppkjp)).
input(policy_password(policy(15-16, c), cccccccccccccctc)).
input(policy_password(policy(1-7, c), vsvkccbc)).
input(policy_password(policy(2-5, h), hhhhchhhhhhhhhh)).
input(policy_password(policy(9-11, n), nnnnnnnnnnnnn)).
input(policy_password(policy(11-12, q), mdmfmkxcxzjq)).
input(policy_password(policy(6-11, m), mmkgnjdhfbc)).
input(policy_password(policy(1-4, d), dgrdwbdfdkdrmthsj)).
input(policy_password(policy(12-14, k), kkkkkkkkkrjkkkkk)).
input(policy_password(policy(2-4, d), hdrvdzd)).
input(policy_password(policy(2-3, s), sxmsssssssssssssssss)).
input(policy_password(policy(13-15, z), zzzzzzlzzlzztzzz)).
input(policy_password(policy(3-8, r), lxrrrnvrtrgnmkrr)).
input(policy_password(policy(6-7, w), wwlbrwwww)).
input(policy_password(policy(4-7, r), zlnmmkpnrkkcrrxrmfq)).
input(policy_password(policy(2-6, v), zgvvjjvvjhjv)).
input(policy_password(policy(8-11, l), llllllllllcl)).
input(policy_password(policy(8-14, m), mlmldmmgnqzmmmm)).
input(policy_password(policy(7-10, z), wzzzzhtzdqzznzz)).
input(policy_password(policy(4-7, k), mvgwkkk)).
input(policy_password(policy(5-9, p), pdpltvdpptpppg)).
input(policy_password(policy(4-15, q), qqqfqbzqlqqqqqpqfqs)).
input(policy_password(policy(5-7, q), qqqcxqqm)).
input(policy_password(policy(14-17, x), rltjxxbxxxllsxwcx)).
input(policy_password(policy(1-13, w), gwggwwwwwwbsbwkwwd)).
input(policy_password(policy(8-14, k), kkbkkkkhkkkxjzblgk)).
input(policy_password(policy(5-8, p), cppnpprp)).
input(policy_password(policy(6-7, k), jrnvhkkgkkb)).
input(policy_password(policy(12-14, h), hhhhhhhhhhhhhn)).
input(policy_password(policy(10-20, j), gjwjjjpjjljjjjjsjjjj)).
input(policy_password(policy(16-17, n), nnnnnnnnnnnnknnnnn)).
input(policy_password(policy(5-6, f), cdpppf)).
input(policy_password(policy(12-13, z), bvpzqzzlwzccfszt)).
input(policy_password(policy(1-9, k), wdkkvtrprltkkltz)).
input(policy_password(policy(9-16, x), xxxjxdxhtzjxgxsbx)).
input(policy_password(policy(17-18, j), jjjjjjjjjjjjjjjjlrxj)).
input(policy_password(policy(2-5, x), xkknmxxxn)).
input(policy_password(policy(3-9, f), tfffhfffffff)).
input(policy_password(policy(11-16, r), rrlgrrqmrrprcrrrvjr)).
input(policy_password(policy(9-12, m), nrlmgmxvgkmpmqvntx)).
input(policy_password(policy(4-7, r), hrrrzrrnm)).
input(policy_password(policy(3-15, g), stgjgbgggvdljcgdgfg)).
input(policy_password(policy(6-9, j), jjjzbpjjjjjj)).
input(policy_password(policy(2-3, p), ppjp)).
input(policy_password(policy(9-10, t), tttttttttt)).
input(policy_password(policy(10-12, w), wwwfwvwvnkwdwww)).
input(policy_password(policy(11-14, d), nvljddddftrndzx)).
input(policy_password(policy(6-7, r), rlrrrbqcrqr)).
input(policy_password(policy(2-4, c), xbdl)).
input(policy_password(policy(11-18, c), ccccccccccvcccccccc)).
input(policy_password(policy(5-6, j), gjjjjjj)).
input(policy_password(policy(3-7, w), xwhnqlhnpfrvlkqqrp)).
input(policy_password(policy(6-19, q), qqqfxdglhqqkqqqjnhdq)).
input(policy_password(policy(8-9, d), ddsdddqsv)).
input(policy_password(policy(14-16, g), gggggggggggggggt)).
input(policy_password(policy(3-5, b), bbbnh)).
input(policy_password(policy(11-14, t), mtttwttfttttltq)).
input(policy_password(policy(8-10, x), xxxcxxxfxq)).
input(policy_password(policy(8-11, l), lfgvnlzrfcllnxss)).
input(policy_password(policy(1-3, t), gtttttttwgtptt)).
input(policy_password(policy(1-20, j), jjgjlqjjcjcjjjsjgjlj)).
input(policy_password(policy(8-14, v), dqgmngvvqnswvvrrvc)).
input(policy_password(policy(2-8, m), gmpkmmsmmmmm)).
input(policy_password(policy(5-6, m), mmmmtm)).
input(policy_password(policy(6-7, z), zfzrxzxz)).
input(policy_password(policy(4-15, k), wmwkhhskgwzqpnk)).
input(policy_password(policy(2-6, d), hddddfzdsdtvg)).
input(policy_password(policy(9-10, g), gggsggggggrgggqg)).
input(policy_password(policy(11-12, m), mmmmmmmmmmmm)).
input(policy_password(policy(5-7, w), wwhqqhwwwwd)).
input(policy_password(policy(4-9, k), gtkrkkkdfk)).
input(policy_password(policy(1-4, g), kgtvg)).
input(policy_password(policy(7-11, r), rhdbzjrwrcr)).
input(policy_password(policy(9-18, f), fjffffffdffkfffffvf)).
input(policy_password(policy(3-5, t), ttttt)).
input(policy_password(policy(13-14, q), qqqqqqqqqqqqcqqq)).
input(policy_password(policy(1-8, n), vnnnnwnqlbln)).
input(policy_password(policy(3-5, s), ssmss)).
input(policy_password(policy(2-4, q), qqqbkvqxh)).
input(policy_password(policy(3-4, n), nshscq)).
input(policy_password(policy(10-18, s), sssssssssnsssssssgs)).
input(policy_password(policy(9-10, v), vvvvvglvzddvvjv)).
input(policy_password(policy(5-16, s), sspssssrssssslss)).
input(policy_password(policy(4-7, t), ttptxtt)).
input(policy_password(policy(2-4, r), rrrrrxdrr)).
input(policy_password(policy(8-9, b), xqvbbbbbh)).
input(policy_password(policy(3-4, b), bbbbc)).
input(policy_password(policy(1-13, v), qhvvvvlvvvvvdv)).
input(policy_password(policy(4-8, l), lhkllblwllll)).
input(policy_password(policy(3-4, q), qhjgq)).
input(policy_password(policy(8-9, p), rpbpppshdpp)).
input(policy_password(policy(13-18, k), kkkkkkkkkkkkkkkkkx)).
input(policy_password(policy(8-9, r), rrrrrrrrr)).
input(policy_password(policy(5-10, f), bjfwwqvjwffpnl)).
input(policy_password(policy(1-3, l), pbhl)).
input(policy_password(policy(4-6, g), mggfgv)).
input(policy_password(policy(1-4, t), tttttt)).
input(policy_password(policy(5-10, t), llqrtccxtttntxjcdczk)).
input(policy_password(policy(13-14, q), qqqqmqqqdqqfqgqqqq)).
input(policy_password(policy(6-10, w), wpwmwwrgwwk)).
input(policy_password(policy(13-16, q), qqshgkqkqvscqtqq)).
input(policy_password(policy(4-5, t), qttdt)).
input(policy_password(policy(2-12, h), fpbbxgpskzjpkvtr)).
input(policy_password(policy(10-12, z), zrszvzzzzrzkznpzw)).
input(policy_password(policy(1-4, z), tgzz)).
input(policy_password(policy(3-6, c), cdwccvgm)).
input(policy_password(policy(1-15, q), jqqxkqrqmtfqpvbpq)).
input(policy_password(policy(4-6, v), vjvlvvv)).
input(policy_password(policy(1-7, l), hjlllwj)).
input(policy_password(policy(6-13, s), lrspslfwsgjks)).
input(policy_password(policy(3-4, p), dpvk)).
input(policy_password(policy(4-8, h), hsjjhhff)).
input(policy_password(policy(1-18, k), pkkkkkkkkkkkkkkkkkk)).
input(policy_password(policy(6-8, n), nvcnxqnnrnnn)).
input(policy_password(policy(7-8, p), ppppppvzp)).
input(policy_password(policy(12-17, h), hhhhhzhhhhhkhhhhph)).
input(policy_password(policy(13-17, p), ppmpppnppppplpbvcppp)).
input(policy_password(policy(8-14, m), tmmcjvmmjgcfmmnj)).
input(policy_password(policy(1-3, t), tttth)).
input(policy_password(policy(3-4, x), zxxx)).
input(policy_password(policy(1-3, d), kpwhxpctcgdbdkb)).
input(policy_password(policy(5-6, z), knnlzzzzxjrghzb)).
input(policy_password(policy(9-10, w), wwmwwwwxgww)).
input(policy_password(policy(9-11, b), bqbbfbbwbbqbb)).
input(policy_password(policy(2-3, d), ddxp)).
input(policy_password(policy(10-12, g), gggvgsgtgggggbg)).
input(policy_password(policy(3-4, b), gbbb)).
input(policy_password(policy(8-20, c), jccqcxjcqfncfcbccgcc)).
input(policy_password(policy(4-9, z), zzzztzzzzzb)).
input(policy_password(policy(2-12, x), gmfmzzrxsqbx)).
input(policy_password(policy(10-12, x), xxxzbxxjxxxkxb)).
input(policy_password(policy(3-4, v), szpvbvlvr)).
input(policy_password(policy(2-5, r), grqqr)).
input(policy_password(policy(4-8, q), mqqnvqvqqq)).
input(policy_password(policy(6-10, v), vdbvnvvxvvvnvvvvv)).
input(policy_password(policy(4-10, d), dddtdddddjd)).
input(policy_password(policy(3-4, l), klmc)).
input(policy_password(policy(10-13, k), kkbkkkvkhkvkkkkkl)).
input(policy_password(policy(1-3, v), vvkz)).
input(policy_password(policy(13-14, h), pkgffgcszgsghbcdtpm)).
input(policy_password(policy(11-16, c), dgccccccctchxbfm)).
input(policy_password(policy(8-9, b), bbbbbbbbbtb)).
input(policy_password(policy(1-9, h), hrnhhlphhh)).
input(policy_password(policy(17-18, s), ssssssssssssssssst)).
input(policy_password(policy(5-10, h), hhhhhzhhhhhx)).
input(policy_password(policy(2-7, k), dlrncbkkwp)).
input(policy_password(policy(3-5, k), kfqkk)).
input(policy_password(policy(4-8, d), ddddddddd)).
input(policy_password(policy(10-15, m), mmmmrmmmlpmmmrgmkmx)).
input(policy_password(policy(2-4, g), gsgggkm)).
input(policy_password(policy(7-9, l), llsllllvrzlxlrgglk)).
input(policy_password(policy(2-9, f), fzfbvfkff)).
input(policy_password(policy(13-14, p), pxppppppppppvf)).
input(policy_password(policy(15-17, z), nbkxkjtszptcndzdl)).
input(policy_password(policy(3-6, z), zzxzzhz)).
input(policy_password(policy(12-13, t), tttttttttttttt)).
input(policy_password(policy(5-10, s), pssbfsbsssnssvsb)).
input(policy_password(policy(9-18, c), ccxthchscjjdccvcncl)).
input(policy_password(policy(3-5, f), fndfqffffff)).
input(policy_password(policy(2-4, m), clwvcdjmz)).
input(policy_password(policy(7-8, b), bbbpbjbb)).
input(policy_password(policy(2-3, r), rbxx)).
input(policy_password(policy(3-8, j), jjjjjjjjj)).
input(policy_password(policy(5-10, v), zrwnvbrvmm)).
input(policy_password(policy(4-6, h), hhghhhhh)).
input(policy_password(policy(6-8, f), fnffzfwfgffpfc)).
input(policy_password(policy(5-6, q), qvqqqqkqqq)).
input(policy_password(policy(3-5, v), vgwvrgqc)).
input(policy_password(policy(9-10, p), pppphbbpphppb)).
input(policy_password(policy(10-12, l), rdjrcxkgflll)).
input(policy_password(policy(9-14, h), qwwxnhfhnfhhbhhjr)).
input(policy_password(policy(9-10, d), ddddpddddd)).
input(policy_password(policy(4-13, w), wwwwwwwwwwwwwwww)).
input(policy_password(policy(8-16, x), xrxxxxxxxdlxxxxxxx)).
input(policy_password(policy(6-10, p), pplppkpzwb)).
input(policy_password(policy(5-7, j), wpjjjgjjvjqjrgj)).
input(policy_password(policy(4-13, w), cwwswwwwwjwwdvw)).
input(policy_password(policy(5-6, j), jjjsjjj)).
input(policy_password(policy(4-5, c), ccfccqdqctllbm)).
input(policy_password(policy(7-13, c), bcccccccccccccc)).
input(policy_password(policy(4-5, p), pgptw)).
input(policy_password(policy(1-4, p), qpwmp)).
input(policy_password(policy(3-5, f), fftfff)).
input(policy_password(policy(2-6, m), mmhbpmjlx)).
input(policy_password(policy(9-13, r), zrrczrlrzqxrszrrlrr)).
input(policy_password(policy(2-9, w), xrszwwwdkww)).
input(policy_password(policy(6-14, g), qlwswsgjdlgmzvwg)).
input(policy_password(policy(6-8, z), zzzzzzfz)).
input(policy_password(policy(6-7, w), xwzsjjr)).
input(policy_password(policy(2-13, f), fxmfdnfffkpggz)).
input(policy_password(policy(1-7, d), rdnlqdplfddjdd)).
input(policy_password(policy(11-14, j), kjjvjjjxpjjjjjzjjjz)).
input(policy_password(policy(12-14, p), gpppwvmqpfpptpfppkpc)).
input(policy_password(policy(6-11, k), kkkkkhkknkkkkkgk)).
input(policy_password(policy(2-6, m), swpgmf)).
input(policy_password(policy(1-3, x), sxzqnxxv)).
input(policy_password(policy(12-18, n), nnnnlnnnnnnnnnnjnxnn)).
input(policy_password(policy(3-4, p), pppq)).
input(policy_password(policy(8-9, v), vvvvvvvpv)).
input(policy_password(policy(6-9, l), ltsldwtlhll)).
input(policy_password(policy(11-14, x), xxxxlxxhdtxxxxxsxx)).
input(policy_password(policy(4-5, q), qsqvqvq)).
input(policy_password(policy(5-6, b), sbbbbt)).
input(policy_password(policy(10-13, l), lllllslllrllll)).
input(policy_password(policy(1-5, m), zmmmmmmm)).
input(policy_password(policy(2-10, s), ssssssssss)).
input(policy_password(policy(5-8, r), qqcsbjcrljvksc)).
input(policy_password(policy(11-15, n), bndcnknnxnnnnnbn)).
input(policy_password(policy(14-15, v), tvvvvvvvvhqwvvv)).
input(policy_password(policy(2-3, s), jsvcsb)).
input(policy_password(policy(12-15, d), mddddfddddlxddddd)).
input(policy_password(policy(12-18, w), wwznwcgwwwwwwhwwgwgw)).
input(policy_password(policy(2-9, v), dxlvvlvqg)).
input(policy_password(policy(2-5, h), njpsxr)).
input(policy_password(policy(11-13, m), rmmmmmmqmmzmtmm)).
input(policy_password(policy(4-8, m), smmmmmmm)).
input(policy_password(policy(3-10, j), ngwtkjfrjjtrxfnvj)).
input(policy_password(policy(2-3, p), ppwwpp)).
input(policy_password(policy(3-5, c), cbmcncnqc)).
input(policy_password(policy(11-13, m), mmmmmmmmmmcmm)).
input(policy_password(policy(4-14, g), gggggggggggggxg)).
input(policy_password(policy(2-4, b), bbfb)).
input(policy_password(policy(16-19, p), ppppppppcppdpppmppwp)).
input(policy_password(policy(10-12, g), gghgxgkvggrggrg)).
input(policy_password(policy(1-8, b), wjjqktjbbfkdz)).
input(policy_password(policy(8-11, c), cqccdcncfcccnc)).
input(policy_password(policy(2-10, z), qzvlqltzns)).
input(policy_password(policy(3-7, p), kgpmpzpbx)).
input(policy_password(policy(1-6, m), mxmdmlmmzmmmmmmmmm)).
input(policy_password(policy(1-7, r), rrrrrrrrrrrc)).
input(policy_password(policy(8-10, h), whhhqhhhjjhnch)).
input(policy_password(policy(6-10, x), xwxxxxkpxdkdnxvh)).
input(policy_password(policy(10-12, z), zzzzzzkzzpzzzzz)).
input(policy_password(policy(1-12, s), dssssssssssds)).
input(policy_password(policy(4-7, f), fvzbfcf)).
input(policy_password(policy(5-6, w), fwwxfwmswxkd)).
input(policy_password(policy(14-15, g), gggggggzgggggfhg)).
input(policy_password(policy(6-7, j), jjjjjnb)).
input(policy_password(policy(1-6, v), vcgksvnrbgsvkrwsc)).
input(policy_password(policy(6-15, w), wkvwwwpqwwwbtwxvhw)).
input(policy_password(policy(8-9, m), smmmmmmmmm)).
input(policy_password(policy(14-15, r), rrjrlrrrrrrrrzbr)).
input(policy_password(policy(3-8, w), tjqncxsnqkdpwzm)).
input(policy_password(policy(4-5, k), kkkkk)).
input(policy_password(policy(8-11, z), zzzzzzpzzxzzkzglzrz)).
input(policy_password(policy(5-6, k), kkkktzk)).
input(policy_password(policy(18-20, w), wwwscwwwwwwwwwwwwgws)).
input(policy_password(policy(1-12, z), dsfxzctdzzjxbt)).
input(policy_password(policy(14-15, q), qqqqqdqqqqqqqqq)).
input(policy_password(policy(7-10, r), rrxrrqrrxcbr)).
input(policy_password(policy(1-13, d), fmgjzgqhdhddd)).
input(policy_password(policy(4-6, g), mnggxttn)).
input(policy_password(policy(6-7, v), gwtmscl)).
input(policy_password(policy(11-14, g), gggnmgggggjggcgggrgg)).
input(policy_password(policy(17-18, k), gcslskskkkwkwkklkk)).
input(policy_password(policy(14-16, r), rrrrrrrrrrrrrbbrr)).
input(policy_password(policy(13-15, s), sjsxszssgfssdgwsbbsp)).
input(policy_password(policy(1-9, d), dddddddddddd)).
input(policy_password(policy(1-13, j), mnjjzckxzjjdj)).
input(policy_password(policy(1-2, j), hwrqjxxcj)).
input(policy_password(policy(6-7, z), fzzzwxnnrg)).
input(policy_password(policy(2-10, x), wxnqjddpxxpxw)).
input(policy_password(policy(3-10, s), srvvssdcvzfn)).
input(policy_password(policy(3-11, w), gwwwmwvwwww)).
input(policy_password(policy(3-4, q), qnqs)).
input(policy_password(policy(11-12, d), dddqdddzdrddddd)).
input(policy_password(policy(2-15, l), wldlltxhrwzzlhz)).
input(policy_password(policy(4-7, g), vgsgkfgmc)).
input(policy_password(policy(7-9, t), jdsltcgttdttd)).
input(policy_password(policy(9-10, q), xvqjqqqwqqqqqpqq)).
input(policy_password(policy(6-9, b), bbkbnbgbbb)).
input(policy_password(policy(2-5, t), ttcjtbkb)).
input(policy_password(policy(7-8, r), rdrrqrnrrrrrvp)).
input(policy_password(policy(2-4, f), pnfqfffvpfffffhbffv)).
input(policy_password(policy(10-12, z), kzzzzzzzzrzpzszz)).
input(policy_password(policy(4-5, m), tmmgxlm)).
input(policy_password(policy(3-4, k), kwhhk)).
input(policy_password(policy(1-11, h), hhhndhhfhvhchmmqhz)).
input(policy_password(policy(6-9, m), lmmmmmmmtmmm)).
input(policy_password(policy(1-5, d), dwdkd)).
input(policy_password(policy(5-6, d), dddddq)).
input(policy_password(policy(7-9, j), jjjvgvmjdjbjj)).
input(policy_password(policy(3-6, w), gwzhpjwkg)).
input(policy_password(policy(10-11, h), hhlmftlhkhhnh)).
input(policy_password(policy(8-20, h), hhgnchpthzhhhhqqwhcz)).
input(policy_password(policy(6-7, s), sssssgfs)).
input(policy_password(policy(3-11, g), jfgqgbvqppjn)).
input(policy_password(policy(5-6, d), ddqkmbd)).
input(policy_password(policy(14-15, h), hhhhhhhhhhhhhphhh)).
input(policy_password(policy(12-13, l), fwkwphdlwmfwg)).
input(policy_password(policy(3-4, z), pmbncwz)).
input(policy_password(policy(3-4, w), lgwv)).
input(policy_password(policy(3-4, s), sshs)).
input(policy_password(policy(2-7, z), zzflznzzzlzl)).
input(policy_password(policy(1-2, k), klbjvbwpkkptb)).
input(policy_password(policy(17-18, r), rrrrrrrrrrrrrrrrlrr)).
input(policy_password(policy(7-8, l), mlqgltml)).
input(policy_password(policy(9-14, l), llljlllxllllvl)).
input(policy_password(policy(5-13, b), bbbbtbbbbbbbfbbbg)).
input(policy_password(policy(7-10, d), cddlddgdqkld)).
input(policy_password(policy(4-6, q), kqqqqq)).
input(policy_password(policy(5-11, r), rrrvrrrsrjrr)).
input(policy_password(policy(7-10, t), tttgtltttbt)).
input(policy_password(policy(13-14, h), hhhhhqhhhhhhndh)).
input(policy_password(policy(3-4, s), dsss)).
input(policy_password(policy(6-12, w), jwwtxwwwkkwbw)).
input(policy_password(policy(7-8, v), cvvgnvvv)).
input(policy_password(policy(12-16, q), qqqqqqqqxvqqqrqqqq)).
input(policy_password(policy(6-11, z), zzkvzvzzzxzzzz)).
input(policy_password(policy(4-9, s), lcrvsssmfs)).
input(policy_password(policy(6-13, c), ccccpdcbcbcgdcccgdcc)).
input(policy_password(policy(7-9, q), qpqqqqqqhq)).
input(policy_password(policy(1-10, k), kwfkkxrkwhtmkwknkx)).
input(policy_password(policy(9-20, x), dxzrxxxsxxxjxxsxdczx)).
input(policy_password(policy(15-16, c), ckcccdccccccgccdcccn)).
input(policy_password(policy(2-7, s), sscxswskxhchxpfs)).
input(policy_password(policy(2-3, h), hhlh)).
input(policy_password(policy(2-6, p), ppppppp)).
input(policy_password(policy(6-8, r), ztmrsjqtrk)).
input(policy_password(policy(1-2, r), drsdvpmzdn)).
input(policy_password(policy(6-7, v), vqvvvgp)).
input(policy_password(policy(5-6, g), gggggg)).
input(policy_password(policy(3-7, d), tfkddmjzjgdxzlkd)).
input(policy_password(policy(16-17, b), bbwbbbbbbbbbbbwbt)).
input(policy_password(policy(2-11, b), hbrwqqhkcrbbvmx)).
input(policy_password(policy(5-11, f), ffffqfffffffff)).
input(policy_password(policy(2-5, n), nnwhn)).
input(policy_password(policy(8-11, j), jxjsjjmjkjkjhjx)).
input(policy_password(policy(1-3, h), hhhh)).
input(policy_password(policy(5-12, t), pttttszttwvlt)).
input(policy_password(policy(7-8, q), mqqqqqqqtkq)).
input(policy_password(policy(7-10, z), xzzzzzdzzzzzzzz)).
input(policy_password(policy(6-7, l), ljzqklhmm)).
input(policy_password(policy(3-5, k), bkkkrk)).
input(policy_password(policy(6-8, x), xxxxxlxcxxxbx)).
input(policy_password(policy(6-7, j), jjqjcpjfjj)).
input(policy_password(policy(8-9, l), cwmllhslwv)).
input(policy_password(policy(14-15, z), zzzzzzzzrzzzzcz)).
input(policy_password(policy(11-12, f), sfccmxxffsfg)).
input(policy_password(policy(5-6, q), qqqqqqqq)).
input(policy_password(policy(12-15, t), tttttttttttttttt)).
input(policy_password(policy(7-12, q), pqwsnhqfzdtqxd)).
input(policy_password(policy(4-5, b), fbcbb)).
input(policy_password(policy(5-7, t), tttstft)).
input(policy_password(policy(2-4, h), vjmr)).
input(policy_password(policy(4-6, r), rrfrprr)).
input(policy_password(policy(18-19, x), xxkxxxxxxxxxxxxxxxxx)).
input(policy_password(policy(2-4, k), qklkc)).
input(policy_password(policy(3-6, s), svjsrs)).
input(policy_password(policy(14-15, j), pjjjhjjjjjjdjgj)).
input(policy_password(policy(2-15, l), lhllllllllllllwlll)).
input(policy_password(policy(2-7, q), qvqqgsq)).
input(policy_password(policy(2-6, z), zzlzzzn)).
input(policy_password(policy(8-15, p), pppppppspppzppgp)).
input(policy_password(policy(3-4, l), kfzbl)).
input(policy_password(policy(9-12, w), hqjwwtdwwlwwmw)).
input(policy_password(policy(3-4, k), lghgg)).
input(policy_password(policy(3-5, k), khgzkk)).
input(policy_password(policy(2-10, r), rrsjlmrsrr)).
input(policy_password(policy(2-5, j), jjjjj)).
input(policy_password(policy(10-12, j), jfgzbdbjwhjjjf)).
input(policy_password(policy(1-4, f), ffff)).
input(policy_password(policy(9-10, j), jjjwjjwzgtcjzj)).
input(policy_password(policy(1-6, m), mmmmmq)).
input(policy_password(policy(5-6, h), hhwhph)).
input(policy_password(policy(3-6, w), wwpwwz)).
input(policy_password(policy(5-6, q), qqqkcb)).
input(policy_password(policy(8-9, f), ffffffxrff)).
input(policy_password(policy(13-14, m), lqvpbrhgmxmkgj)).
input(policy_password(policy(4-6, q), pqqxqk)).
input(policy_password(policy(7-11, b), mbbnsvbbjbbmb)).
input(policy_password(policy(17-18, q), qqqqqqqqqqhqqqqqqqq)).
input(policy_password(policy(3-12, w), qzcwxswwzvwzb)).
input(policy_password(policy(10-11, l), llllllllxxs)).
input(policy_password(policy(1-4, c), bvcch)).
input(policy_password(policy(11-13, s), svssqfvssshst)).
input(policy_password(policy(6-7, l), lllllrl)).
input(policy_password(policy(5-8, n), nhqkfnggnpkbhpgntlht)).
input(policy_password(policy(1-14, g), pgrdgjggggpggc)).
input(policy_password(policy(12-16, n), hlnhkxpnnsfctsnq)).
input(policy_password(policy(6-8, c), cccftqcfqc)).
input(policy_password(policy(1-5, f), fbfff)).
input(policy_password(policy(1-15, t), mttptftctttptttt)).
input(policy_password(policy(6-11, t), cxtttnnfttt)).
input(policy_password(policy(7-11, h), hsrfjswhhhhhhhhc)).
input(policy_password(policy(12-13, b), bbbbbbbbbbbnfbvb)).
input(policy_password(policy(12-13, x), lzvxjxxxcxxxq)).
input(policy_password(policy(12-13, p), ltwhhhqvdjptbsw)).
input(policy_password(policy(7-9, z), zzzzzztzn)).
input(policy_password(policy(4-5, g), ggqlgg)).
input(policy_password(policy(8-10, r), rbqxwzfhlzt)).
input(policy_password(policy(3-5, g), grhgk)).
input(policy_password(policy(14-19, z), zrzzbzztszpzvzbdfzm)).
input(policy_password(policy(7-11, d), tdjbcdpdddb)).
input(policy_password(policy(3-7, j), jpqjjjj)).
input(policy_password(policy(1-2, m), mcxklcmmws)).
input(policy_password(policy(7-8, r), drqlcrfqrgrrxrrg)).
input(policy_password(policy(1-5, g), kgngw)).
input(policy_password(policy(8-10, r), wrrbfrrrpntjrrrgrr)).
input(policy_password(policy(1-4, s), sstf)).
input(policy_password(policy(3-7, b), fnjnpmfjlwb)).
input(policy_password(policy(2-5, s), pwjkj)).
input(policy_password(policy(9-11, t), tbtbtrsrfzntwqq)).
input(policy_password(policy(13-16, m), mmmmmmmmmmmmmmmmm)).
input(policy_password(policy(13-18, b), bbbbbbbpqlbbbtbtpxb)).
input(policy_password(policy(9-11, w), wclwwwrwwwkhww)).
input(policy_password(policy(7-13, b), bbbbbbbwbbbbb)).
input(policy_password(policy(8-12, t), sxlwtttttnhn)).
input(policy_password(policy(4-7, q), kmdqxcqswqw)).
input(policy_password(policy(3-4, r), rjrr)).
input(policy_password(policy(4-6, m), mdmdmmmm)).
input(policy_password(policy(6-17, h), kjrkchhnfhqqcrmhhhdh)).
input(policy_password(policy(6-9, j), vjjgcjjjpdj)).
input(policy_password(policy(7-9, x), xxxxsxxxxx)).
input(policy_password(policy(8-16, j), jjjjjgjnjjjjjjjczd)).
input(policy_password(policy(6-8, t), tttttttd)).
input(policy_password(policy(7-17, s), ssmsspvsssspssssfssl)).
input(policy_password(policy(3-10, f), cgffsqxhdmrvdf)).
input(policy_password(policy(1-3, f), wfpf)).
input(policy_password(policy(11-12, k), kkkkkkkkkkfqk)).
input(policy_password(policy(12-15, s), cxghswzsbttmvpscr)).
input(policy_password(policy(3-4, n), nnkn)).
input(policy_password(policy(7-17, w), wwlwnxwxwwswwwwwg)).
input(policy_password(policy(3-10, h), hhvhhhrhhhfghhcn)).
input(policy_password(policy(10-11, l), lllxlllllllsl)).
input(policy_password(policy(5-7, d), ddbddtddv)).
input(policy_password(policy(5-15, g), ggtggqggggzggggwggv)).
input(policy_password(policy(2-10, r), mrpdmtrzsrngstsr)).
input(policy_password(policy(9-15, t), bsbptttttqwzmmtgbgm)).
input(policy_password(policy(8-10, q), qqqqqqqqqqq)).
input(policy_password(policy(6-9, h), hlrbcsnhh)).
input(policy_password(policy(12-17, f), ffkjfffffffnftfmf)).
input(policy_password(policy(11-12, s), ssssssssssss)).
input(policy_password(policy(9-15, k), hpkskfkkfkkkkbkk)).
input(policy_password(policy(8-18, b), bbbbbbdbbbbbbjbbjw)).
input(policy_password(policy(2-14, p), nppppkkppppppw)).
input(policy_password(policy(11-12, s), sxhtlrtnbgss)).
input(policy_password(policy(8-10, q), lnwqqqqqqsqhgqgbq)).
input(policy_password(policy(2-3, l), llll)).
input(policy_password(policy(14-17, d), gdddtlfmrdscgsqcmkm)).
input(policy_password(policy(5-8, w), tmmskwpq)).
input(policy_password(policy(16-17, b), cbbbpzbbrrbnkbbbbgj)).
input(policy_password(policy(14-17, b), bbbjbbbbbbbxbvbdszbb)).
input(policy_password(policy(9-10, q), qqqqqtqqqqr)).
input(policy_password(policy(5-6, t), ctgttztrtn)).
input(policy_password(policy(2-3, f), gcfgw)).
input(policy_password(policy(3-8, d), ddzddddsddddddd)).
input(policy_password(policy(15-16, g), ggggggjggggggggg)).
input(policy_password(policy(4-10, m), mcmmmmmmmmmvmmmm)).
input(policy_password(policy(11-15, p), ptppxjppppmkgpvdp)).
input(policy_password(policy(12-13, n), nnnnnnnfnnnrn)).
input(policy_password(policy(1-7, t), tnbwtttmtt)).
input(policy_password(policy(1-14, c), ndncvjbkcmcjplcp)).
input(policy_password(policy(1-2, f), fffh)).
input(policy_password(policy(14-17, t), llzkwltkmdntwndqs)).
input(policy_password(policy(4-7, w), bffzzwdwtkwwv)).
input(policy_password(policy(4-8, p), zpbpqpppxpb)).
input(policy_password(policy(8-14, n), fdnnznhnnlhmtn)).
input(policy_password(policy(7-14, l), vltrjnzhplkshlt)).
input(policy_password(policy(1-2, d), ddbhsjtv)).
input(policy_password(policy(2-10, d), dddddbzrdrdd)).
input(policy_password(policy(4-10, p), pkppshsfmp)).
input(policy_password(policy(10-11, g), gmgggzvzmgjgggzqxggd)).
input(policy_password(policy(2-4, j), fjvjjqf)).
input(policy_password(policy(5-19, h), cstkhhrctkxhhsfzpph)).
input(policy_password(policy(6-16, s), sssssssssssssssks)).
input(policy_password(policy(17-18, v), vvvvvvvvsvvvvvvvtv)).
input(policy_password(policy(2-5, j), zjjjjj)).
input(policy_password(policy(2-3, r), xrrrqlxl)).
input(policy_password(policy(17-19, c), cccrcccgcwcchccccdcc)).
input(policy_password(policy(7-14, l), lllllllllllllcsl)).
input(policy_password(policy(12-14, p), jlmhpjgdzjkpnbmnbk)).
input(policy_password(policy(17-18, n), nnnnnnnnnnnnnnnnqv)).
input(policy_password(policy(8-10, b), lqzrtbzbrb)).
input(policy_password(policy(8-11, x), xgxxfxxxxkxx)).
input(policy_password(policy(5-9, x), xxxsnxnxk)).
input(policy_password(policy(2-11, t), stxbxwssmgthttx)).
input(policy_password(policy(6-13, t), ktbktrtqcnlrgtvtwt)).
input(policy_password(policy(10-12, q), qqqqqqqqqrqq)).
input(policy_password(policy(14-15, q), znptzmgllrfrqrf)).
input(policy_password(policy(2-13, f), ffffffcffffff)).
input(policy_password(policy(9-10, h), hrbhnhhhhhhhh)).
input(policy_password(policy(8-14, k), lskskkkfzkkkkmkkm)).
input(policy_password(policy(1-3, g), kbmswhmghvwvnwxzzk)).
input(policy_password(policy(2-4, v), vttv)).
input(policy_password(policy(2-3, h), qhhmhghbh)).
input(policy_password(policy(6-13, t), ttgtttttktttdttt)).
input(policy_password(policy(7-9, v), vvrrvvvvvv)).
input(policy_password(policy(5-6, z), hcfwdr)).
input(policy_password(policy(5-13, g), sgmgggcggggggjrggggk)).
input(policy_password(policy(10-14, k), kzkkkkkkdskkktkkk)).
input(policy_password(policy(1-2, j), ptjj)).
input(policy_password(policy(4-11, b), xnbbbbnbbbb)).
input(policy_password(policy(14-16, b), bbbbbbbbbbbbbkbc)).
input(policy_password(policy(4-12, w), mwrwrcpwkpzwxrj)).
input(policy_password(policy(5-6, l), qlndzlcvw)).
input(policy_password(policy(1-2, s), ksxk)).
input(policy_password(policy(4-5, p), spgwql)).
input(policy_password(policy(7-10, j), ljjjjvxjhzjjjjrj)).
input(policy_password(policy(6-14, f), ffffffffffffff)).
input(policy_password(policy(11-15, d), ddddddddddzdpdn)).
input(policy_password(policy(3-5, t), ttmtz)).
input(policy_password(policy(6-7, x), kxvxxxx)).
input(policy_password(policy(3-6, m), mhmklm)).
input(policy_password(policy(4-8, h), bnhjhphgqxphpnthh)).
input(policy_password(policy(3-4, w), gwpq)).
input(policy_password(policy(10-13, t), ttvttjhttcttrtthtb)).
input(policy_password(policy(1-5, f), ffffg)).
input(policy_password(policy(6-14, v), rtjjvpbvnvjwlvktvvf)).
input(policy_password(policy(8-9, n), nnknnnxmnnn)).
input(policy_password(policy(9-10, v), vvsvvsvvqcvvpp)).
input(policy_password(policy(9-11, x), xxxxxxxxxwl)).
input(policy_password(policy(3-6, h), bwqxnrhkhhwhhh)).
input(policy_password(policy(4-8, l), lvllrlcf)).
input(policy_password(policy(1-2, m), gtrm)).
input(policy_password(policy(2-4, z), zzzz)).
input(policy_password(policy(6-7, j), jjjjjjj)).
input(policy_password(policy(15-16, g), sggggggggqgclgggmggw)).
input(policy_password(policy(7-9, v), dvmskjsczkvjcpsv)).
input(policy_password(policy(3-11, d), hmdrdfdqrddzdddjdd)).
input(policy_password(policy(7-9, m), mmmwfmmmtmm)).
input(policy_password(policy(6-8, x), lxsbxmlx)).
input(policy_password(policy(3-5, q), qqqxq)).
input(policy_password(policy(5-10, n), nnnnznnnnrn)).
input(policy_password(policy(4-6, m), zmmbzg)).
input(policy_password(policy(10-11, c), cpdndvlfltc)).
input(policy_password(policy(2-4, k), kzkkk)).
input(policy_password(policy(1-14, m), jmmmmmzmqtmsmmnmm)).
input(policy_password(policy(3-13, h), gwhhrlbstldmh)).
input(policy_password(policy(2-5, l), rrlhdqkzst)).
input(policy_password(policy(1-6, s), sqgsjs)).
input(policy_password(policy(3-4, h), hhgpb)).
input(policy_password(policy(11-16, l), llllllllllllllwkllll)).
input(policy_password(policy(7-11, j), gjjjtvhjjpj)).
input(policy_password(policy(14-15, h), hjjvmbhfjhhxkbh)).
input(policy_password(policy(1-2, t), rwxgz)).
input(policy_password(policy(13-18, p), pppppppppppppppppppp)).
input(policy_password(policy(1-14, x), xxrxxjxhxxxxxxbxxx)).
input(policy_password(policy(4-6, b), fbzsbpbbb)).
input(policy_password(policy(12-16, j), fjjgmnjwbvhjzzzs)).
input(policy_password(policy(6-7, m), mmmmmtq)).
input(policy_password(policy(12-16, n), nnmnnpnnnnnknqxkjnjn)).
input(policy_password(policy(5-8, w), wmwwwwpwlwllzwkcw)).
input(policy_password(policy(7-10, q), gbpsnqwqfm)).
input(policy_password(policy(10-13, x), vxxxxxxxxxdqnxx)).
input(policy_password(policy(7-12, q), qqqqqqqqqqqqqqq)).
input(policy_password(policy(1-2, n), snnn)).
input(policy_password(policy(6-10, l), lljllklllwp)).
input(policy_password(policy(3-4, b), bsnjzbb)).
input(policy_password(policy(13-14, g), tggztfgdggngmglgg)).
input(policy_password(policy(6-16, l), bkcwjlwcnfwthlll)).
input(policy_password(policy(8-11, s), sssssssvsss)).
input(policy_password(policy(3-4, k), xmthtrcx)).
input(policy_password(policy(7-8, h), wpmjhbgg)).
input(policy_password(policy(4-5, p), pcpkvp)).
input(policy_password(policy(14-15, s), ssrssssssssssjs)).
input(policy_password(policy(14-15, x), xxxzxxgxxtxxxxqx)).
input(policy_password(policy(6-7, m), nwmfmxmm)).
input(policy_password(policy(6-8, k), hsknkmvhkgkkfzkjf)).
input(policy_password(policy(4-5, s), sssms)).
input(policy_password(policy(7-9, g), gfgqldxgxdjzglcgg)).
input(policy_password(policy(10-11, k), ckkthkzpdrfv)).
input(policy_password(policy(1-14, p), jptppkcppjpppppppp)).
input(policy_password(policy(10-11, x), pxkccxpxdsq)).
input(policy_password(policy(2-8, x), xsgxxxxvgxxk)).
input(policy_password(policy(6-14, j), jjjjjzjjjjjjjtjjjj)).
input(policy_password(policy(7-10, x), rxxnxrzgxxd)).
input(policy_password(policy(6-12, g), dmgggpgggwczggghggm)).
input(policy_password(policy(3-6, h), hdhjhhhhchh)).
input(policy_password(policy(11-12, r), zrrkcrrrrrlh)).
input(policy_password(policy(7-9, v), vhqvlvwvzqwqvrxvjnf)).
input(policy_password(policy(1-5, r), rvmjr)).
