code('BFFFFFFRLL').
code('FFBFBBBRLL').
code('FBBFBFBRLR').
code('BBFBBBBLLL').
code('BBFBBBBLLR').
code('BBBFBBBLLR').
code('FFBBBFBRLR').
code('BBFBFBFLRL').
code('FBBFFBBLRL').
code('BBBFBBFRRL').
code('BBFBBFFRRL').
code('BFBBFBFLRL').
code('BBFFFBBRLL').
code('FBFFFBBLLR').
code('FBFBFBFLRR').
code('FBBFBFFRLL').
code('FFBBFFFRRR').
code('BFBFBFBRLL').
code('FBBFFBBRLL').
code('BBBFFBBRLL').
code('BFBFFFFLLR').
code('FBBBBFBRRR').
code('BBFBBFFLRR').
code('BFFBFBFRRR').
code('FBFBBBBRLR').
code('BFBFBFFRLL').
code('BFFFFFBRLL').
code('FBBBFBFLLR').
code('BFFBFBBRRR').
code('BFFBBFBLLR').
code('FBBBFFBLLL').
code('BFFFBFBLRR').
code('FFFFBFFLRR').
code('BBFFFBFLLR').
code('FBFBFFFLLR').
code('FBFFFFFLLL').
code('FFFFFFBRLL').
code('BFFBFBBLRR').
code('BFBFFBBLRR').
code('BFFBFFBRLR').
code('FFBFBBBLLR').
code('FBFFFBFRRR').
code('BFBFBFFRLR').
code('BBBBFFBRRR').
code('FBBFBBBLLL').
code('FBBBBFBLRR').
code('BFBBFFFRRL').
code('FBBBBBBLRL').
code('FBBFFFFLLL').
code('FFBBBFFLLR').
code('FBBBBBBRRR').
code('BBBBFFBRLR').
code('BBBFBFBLRL').
code('FFBFFBFLLL').
code('FBBBBBFLLL').
code('FFBBBBBRLR').
code('FBBFFFFLRL').
code('BBFBBFBLLR').
code('FFFBBFFRLR').
code('FFFBBBFLLL').
code('BFFFFFFLRL').
code('BFFFBFFLRL').
code('FBBFFFFRLR').
code('FBFFFBBLLL').
code('FFFFFBFRLR').
code('BBBBFBFLLL').
code('FBFBFFBLLR').
code('FFBFBFBRLR').
code('FBBBFBBLLR').
code('FFBBBBFRLR').
code('FBBBFBBRLL').
code('FFFBFBFLLL').
code('FFFFFBFRRL').
code('FFFBFFBLRR').
code('BFBFBBFRLL').
code('BFBFFFBLLL').
code('FFFBFBFRLL').
code('FBFBBBFRLL').
code('FFFBFBFLLR').
code('BFBBFBFRRL').
code('BBFFBFFRLR').
code('FFFBBFFRLL').
code('BBBBFFFLRL').
code('BFFBFBBLLL').
code('BBFFFFFLRL').
code('BBFFBBBRLL').
code('FFBFFFFLRR').
code('FFBBFFFRLR').
code('BBFFBBBRLR').
code('FBFBFFBRRL').
code('FFFFBBBLRL').
code('BBFBFFFRRL').
code('BFBBBFBRRL').
code('FFBFBFBLRR').
code('BBBFBFFRLR').
code('BFBBBBBRRL').
code('FBFFFFFLRR').
code('BFFFFFBLRR').
code('FFBBBFBLLL').
code('FBBBFFFLRL').
code('BBFFBBFRRL').
code('FBFFFFBRRR').
code('BFBFBBBRRL').
code('BBFFBBBLRL').
code('FBBFBFBRLL').
code('FBFBBBFLLL').
code('FFFFBBBLRR').
code('FBBFBBFLLR').
code('FBFFBBFLRL').
code('FFBBFBFRRR').
code('BFFBBBFLRL').
code('FFFBBBFRRL').
code('FFBBBFFLRL').
code('BFBBFFBRLL').
code('BFFBFFFLLL').
code('FBFFFFBLRR').
code('BFBFFBFLRL').
code('FBBFFBFLLR').
code('FBBFBBBRRL').
code('BBFBFFFLLL').
code('FBBBBFFLRR').
code('FBBBFBBRRR').
code('FFFBFFFLLR').
code('BBFFBBFLRL').
code('FFFFBFFRLL').
code('BFBBBFFRRR').
code('BFFFFBFRRL').
code('BBFFBBBLLR').
code('BFBBBBFRRR').
code('BFBBBFFLLL').
code('BBFBFFFLRL').
code('BBBFFFBRRL').
code('BBBBFFBRLL').
code('FBFFFFFLRL').
code('BFFFBBFLLR').
code('FFFFBBFRRL').
code('BBFFBFBLLR').
code('BFFBBFFRRL').
code('BBBFFBBLLL').
code('BFFBFBFLLL').
code('BFBFBFBRRL').
code('BBFFFFBRRL').
code('FBBBFBFRRR').
code('FFBFBBFRLR').
code('FFFBBBBLRR').
code('FFBBFBBRRL').
code('BBFBBFBRLL').
code('FFBBBBBRLL').
code('BFBBBBFLRR').
code('FBFBBFBLLL').
code('FBBFFFFRLL').
code('BFFBFFFLRL').
code('BBBFBBFLLL').
code('BFBFBBBRRR').
code('FBFBBFFLRL').
code('FBBBFFFLLR').
code('FBBBFFBLLR').
code('BBFFBBFRLL').
code('FBBFFBFLRL').
code('BFFBBBFRRR').
code('BFBBBBBRLL').
code('FFBBBBFRLL').
code('BBBFFFFLLL').
code('BBFBFFBRRR').
code('FBBBBFFLLL').
code('BBBFFFFRRR').
code('FBBFBFBLLL').
code('BBBFBBFLRR').
code('FFBFFBBRLL').
code('FFBBFBFLLL').
code('FBFFFFFRLL').
code('FBFBFFBLRR').
code('BBFFBBBRRL').
code('BFFBBBFRRL').
code('FFBBBFBRLL').
code('FBBBBFBRRL').
code('BBFBBBBRLR').
code('BFFBFFBRRL').
code('BBFBFBBRRL').
code('FFFBFBFRLR').
code('FFBBFBFRLR').
code('FFFBBFBRLL').
code('BFFFFBBRLL').
code('FBFBBFBLLR').
code('FBFFBBFLLL').
code('BBFBFBBRLR').
code('BBFBFBBLLL').
code('FBBBFBBRRL').
code('BFFFBBBRLR').
code('BBFFBBBRRR').
code('BFFBFFBLRL').
code('BBFBFFBLLR').
code('FFFFFFBRRL').
code('BFBFBFFLLR').
code('BBBBFFBLLL').
code('FBBBFBFRRL').
code('FBBFFBFLLL').
code('FFBFBFFRLL').
code('BFBBFFFLLL').
code('FBFFFBBLRL').
code('FFFBFFBLRL').
code('BFFFBBBLRR').
code('BBBFFBFRRL').
code('FBBBFFFRLR').
code('FFBBFFBRRR').
code('FBBBBBBLLL').
code('BFFBBFFLLR').
code('FFFFFBBLLR').
code('FBBFBFBRRR').
code('BBBFBFFLLL').
code('FFFFBBFRRR').
code('FBFFFFBRLL').
code('FFBBFFFLRR').
code('FFFFFBBLRL').
code('BBBBFFFLLL').
code('FFFFBFBLLR').
code('BBBBFFFRRR').
code('FBBFBBFRRR').
code('BFFBFFFRLR').
code('FBFFBBFLRR').
code('BFBBFBBRLR').
code('BFFBBBFLLL').
code('BFBFBBBLLL').
code('BBFBBBFRRL').
code('FBBFBBFRRL').
code('FFFBFFFLRL').
code('FBFFBFBLRR').
code('FFBFFFFRLL').
code('FFFFBBFLRR').
code('BFBFFBFLRR').
code('FBBFBBBRLR').
code('BFBBBFFLRL').
code('BBFBFBFRLR').
code('FFFFFBBRRL').
code('BBFFBFFLRR').
code('FBBBFFBRLR').
code('BBBFFBBRRL').
code('FFFFFBBRLR').
code('FFFBBFFRRL').
code('FFBFFFFRLR').
code('BFFBFBBLLR').
code('BFBFBFFLLL').
code('FFBFBBBLRL').
code('BBFBBBBLRR').
code('BFFFFFBRLR').
code('BBFBFBBLLR').
code('FBBBBFBRLL').
code('BBFFBFBLRR').
code('BBFBFBBRRR').
code('BBBFBBBLLL').
code('FBFBBBBRLL').
code('BFFBFBBRLL').
code('BFBBBBBRLR').
code('BBFFFFBRLL').
code('FBFBBBBRRR').
code('FBBFFFBRRL').
code('BFFBBFFLLL').
code('BBFBBFBLRL').
code('FBBFBBBLRR').
code('FBBFBBFLLL').
code('FFFFBBFLRL').
code('BFFFBBBRLL').
code('FFFBBBFLRL').
code('BFFFBBFRLR').
code('FFFFBBBLLR').
code('FFFFBFFRLR').
code('FFFFBBBRRR').
code('BFBFBFBRRR').
code('BBFFBBFRRR').
code('FBBFBFFLLR').
code('BFBBBFBRLL').
code('BFBFFFFRLR').
code('BFBFFFBLLR').
code('BFBBBFBRRR').
code('BFFBBBFRLL').
code('FBFFBBFRLR').
code('FBFBBFFLLL').
code('FBFBFFFRLR').
code('FFFBFBBLRR').
code('FFBBBFFRRL').
code('BBFBFFBLRL').
code('FBBBBBFRLR').
code('BBBFBFBLLR').
code('FFFBBFFLRL').
code('BFFBBFFLRR').
code('BBFBFFFLRR').
code('FFBFFFBRRR').
code('BFFBBFBLRL').
code('FFBBFFBRLL').
code('BFBFFBFRLL').
code('FFBFBFFRLR').
code('FBFFFBFRLR').
code('BFBBFBFRLL').
code('BFFBFBFRRL').
code('FFBBFFBRRL').
code('FBFFFFBLLL').
code('BFFFBBBLLL').
code('FBBFBFFRRL').
code('BFBFBBBRLL').
code('FFFBFFFLLL').
code('BFFFBFFRRL').
code('FBBBBBFRLL').
code('FFBFBBFRRR').
code('FBFBFFFLLL').
code('FFFBFBBRRR').
code('BFBBFFFLRR').
code('FFFFFBFLRR').
code('FBFBFFBRLR').
code('FBFFBBFLLR').
code('BBBFFFBLLR').
code('FBFFFBBRLL').
code('BFFBFBBLRL').
code('FFFFFFBRRR').
code('FFBFBFBRLL').
code('BBFBBFFLLR').
code('BBBFFFFRLR').
code('BFBFBFBLRL').
code('FBFFBFBRLR').
code('FBBFFFBRRR').
code('BBFFFFFLRR').
code('BFBFBFBLRR').
code('BFBBBBBLLR').
code('FFBFFBFRRR').
code('FFFFBBBRLL').
code('FBBBBBFLRR').
code('FFBBFBFRLL').
code('FBFBBFFLRR').
code('FFBFBBBLLL').
code('FBFFBFFRRL').
code('BBBFFBBLRR').
code('BFFFFFFRRL').
code('FBFFBFFRLL').
code('FBBBBFBRLR').
code('FBBBFBFLRL').
code('FBBBFFBLRL').
code('FFBBFBBLLR').
code('BBFFFBBRLR').
code('BBBBFFBLLR').
code('BFFFFBFLRR').
code('BBFFBFFRLL').
code('FFBFBFFRRR').
code('BFFFFFFRLR').
code('FFFFBFFLRL').
code('BFBBFFFRLR').
code('BBFFBFFLLL').
code('FFFFFBFRRR').
code('FFFBFBBLRL').
code('BFFBBBBRRL').
code('FBFBBFFLLR').
code('FFFBBFFLLL').
code('FFFFBFBLRL').
code('BBFBFBBLRR').
code('BBFFBFFLRL').
code('BBBFFFBLRL').
code('BFFBFBFRLL').
code('FFFBFFFLRR').
code('FBFFFBBRLR').
code('BFFFBBFRRR').
code('FBBBBBFLRL').
code('BFFFBBBLLR').
code('BFFFBBFLRL').
code('BFFFFBFLLR').
code('FBFFFBBLRR').
code('FBBFFFBRLR').
code('BBFFBFBLRL').
code('BBFBFBFLLR').
code('FBBBFBFRLR').
code('FBFFFBFRRL').
code('BFFFBFFLRR').
code('FFFFBFBLRR').
code('FBFFBFFLLL').
code('FFBFFBBRLR').
code('BBFBBBFLLL').
code('FBFFBFBRRL').
code('BFFBFFBRLL').
code('BFBFFFFLRR').
code('FFBFBBBRLR').
code('BFFBFBBRRL').
code('FBFBBBBLRR').
code('BFFFFFBLLL').
code('FBFFBFBRRR').
code('FBFBBFFRLR').
code('BFBFBBFLLL').
code('BFBBBFFRRL').
code('FFBBBFBLLR').
code('FBBFFFBLRL').
code('BFFFFFFLLR').
code('FBFFFFBLRL').
code('FFBBFFFLRL').
code('FFBBBFBLRL').
code('BFFFBFBLLR').
code('BFFBBBFLRR').
code('FBFFFBBRRR').
code('FFBFFFBRLL').
code('FBFBFBBLLR').
code('BFBBBBFRLL').
code('FBBBBFFRLL').
code('BFBFFBFRRL').
code('FBBBBFFRLR').
code('FFBFFFFRRR').
code('BFFFBBFLRR').
code('BBFBFBFRLL').
code('BFFBFFBRRR').
code('FFFFFBFLLL').
code('BFBFFFBRRL').
code('BFFBBFBRRL').
code('BFBBFFBRRL').
code('FFFBBBBRLR').
code('FFFBBBBLRL').
code('BFBBBFFLLR').
code('BFBFFFFRRR').
code('BBBFBFFRRR').
code('FFFBFFFRRR').
code('FFFBFBBLLR').
code('BBBFBFFRRL').
code('BBFFBFFLLR').
code('FFFBBFFLLR').
code('FFFBFBBLLL').
code('FBFBFBFLRL').
code('FFFFFBBLLL').
code('FBBBBBBRLR').
code('FFBBFBFLRL').
code('BFFFFBBRLR').
code('BFFFBFBLLL').
code('BBFBBBFRRR').
code('FBBBFFBRRL').
code('FFBFFBFLRL').
code('FFBFFFFLRL').
code('BBFFFFBLLL').
code('BFBBFBBRLL').
code('FFFFBFFRRR').
code('BFFBFBBRLR').
code('BFFBFBFLRR').
code('BFFBBFBRLL').
code('FBBBFBBLRR').
code('FBFBFFFRLL').
code('BFBFFFBRLL').
code('FBBBBBFRRL').
code('FBFBFBBRLL').
code('FBBFFBBRRR').
code('BFFFBBFRRL').
code('BBFFFFFRRR').
code('BFFBFBFLRL').
code('BBBFFBBLRL').
code('FFBFBBFLRR').
code('BBFFFBFRLR').
code('FBFBBBFRRR').
code('BBFBBBBRLL').
code('FBFFBFFRLR').
code('BFBBBFFRLR').
code('FBFFBBBLRR').
code('BFBFFBFRRR').
code('FFBFFBFRRL').
code('FFBBBBBLLL').
code('BBFBBBFRLL').
code('BFBBFBBLLL').
code('BFBBBFBLRL').
code('FBBBFBFLLL').
code('FBBFBFFLRL').
code('FBFBFBFLLL').
code('BBFFBBFRLR').
code('FBFBBBFLRL').
code('BBFBBFBLRR').
code('FFFFBFFLLL').
code('FFFBBBBRRL').
code('BBBFBBBRLL').
code('BBFFFFFLLR').
code('FBBFFBBRLR').
code('FBBFBBFRLR').
code('BFFFBFBLRL').
code('BFFFFBBRRR').
code('FBFFFFFLLR').
code('FBBFBBFLRL').
code('BBFFFBFRRR').
code('BBBFFBFLLR').
code('BFFBBFBRLR').
code('BBFBFFFRLL').
code('FFFBBFBLRR').
code('BBBFBFFLLR').
code('FBFFBFBLRL').
code('FBBFBFFLRR').
code('FBBBFFFLRR').
code('FBBFBBBRRR').
code('BBFFFBFRLL').
code('FFBFBBFLRL').
code('FBBFFFBLLR').
code('BFFFFBFRRR').
code('BBFBBFFRLL').
code('FFBFBBBLRR').
code('BFBFFFBLRL').
code('FBBFFBFRRL').
code('FFFFBBBRRL').
code('FFFBBFBRRR').
code('FFFBBBFRLL').
code('BBFFBBFLLR').
code('FFBFBFFRRL').
code('BFBFFFBRLR').
code('FFBBBFFRLL').
code('FFFFBBFLLL').
code('BFFFFFBLLR').
code('FBBFFFFRRR').
code('FFFFFFBLRL').
code('BBFBFFFLLR').
code('BBBFBFFLRL').
code('BBBFFFFRLL').
code('BBFFFFBRLR').
code('FBFBBFFRRL').
code('FFFFFBFLLR').
code('BFFFBFBRLR').
code('BFFFFFFRRR').
code('FBFBFBBRLR').
code('BBBBFFFRLR').
code('FBBFBFBLRL').
code('BBFFBFFRRR').
code('BFFBBBBRLR').
code('BBBBFFBLRR').
code('BFBBFBBRRL').
code('BFFFFBBLLL').
code('BFFFBFBRLL').
code('FBBFFFFLLR').
code('BFBBFFFRLL').
code('BBFBBBFRLR').
code('FBFBFBFRRR').
code('BFBFBFFLRR').
code('BBFBBBBRRL').
code('BFFFBFFRLR').
code('BBBFBFBLLL').
code('FBFBFFFRRL').
code('FBBBFFFRLL').
code('FBFBBFBRRR').
code('FBFFFFFRRR').
code('FBBBBBBRRL').
code('BBBBFFFLLR').
code('BFFFBFFLLR').
code('BFBBFBBLRL').
code('BBBFFFBRLR').
code('FFFBBFBLRL').
code('BFBFBFFRRR').
code('BBFFFBBLLR').
code('FBFBBFFRLL').
code('FFFBBBFRLR').
code('BFFFFBFRLL').
code('FFBBFBBRLL').
code('FFFBFFBRRL').
code('BBBBFFFRLL').
code('FBFFBBBRLL').
code('FFBFBFFLLL').
code('BBBFBBFLRL').
code('FBFBBFBLRL').
code('FFBFBFFLRR').
code('FFFBFFBLLR').
code('FBBFBFFRRR').
code('FFBFBFBLLR').
code('FFFFFFBLLR').
code('BBBFFFFLRR').
code('BBFBBFFRLR').
code('FFFFBBBLLL').
code('FBBFFFBLRR').
code('BFFFFBFLLL').
code('BFBBBFBLRR').
code('FBFFFBFLLR').
code('FBFBBFBRRL').
code('BFBFBBFRRR').
code('FBFBFFFLRR').
code('FFBFFBFLLR').
code('FBFBFBFRRL').
code('FFFBBBFLRR').
code('FFFBBBBLLR').
code('BBBFBBFRRR').
code('BFFBBBBLRR').
code('BBBFFBFLRR').
code('FFBBBFFRRR').
code('FBFFBFFRRR').
code('BFFFFBBLRR').
code('BFFBFFFRLL').
code('BFFBFFBLRR').
code('FBBBFBBRLR').
code('BFBFFBBRLR').
code('FBFFBBFRRR').
code('FFBBBFFRLR').
code('BBFFFFFRRL').
code('BFFBBBBLRL').
code('FBBFFFFLRR').
code('FFBFBBFLLL').
code('BFFFBBBRRR').
code('BBFFFFBLRR').
code('FFFFBFBLLL').
code('FBFFBFFLRR').
code('BFBFBFFLRL').
code('BBFFFFFRLR').
code('BBBFFBBRLR').
code('BBFFBFBRRR').
code('FBFFBBBLLR').
code('BBFBFBFRRR').
code('BFBBFBFRRR').
code('BFFFBBBLRL').
code('BFBBFBBLRR').
code('BBBFBBBRRR').
code('FFFBBFBRRL').
code('FFBFFFBRRL').
code('FFBFBFBLRL').
code('BFFFFFBRRR').
code('BFBFBBBLLR').
code('BFFFBFFRRR').
code('FBFBFFFLRL').
code('BFBBBBBRRR').
code('FFFBFBFLRL').
code('FFFFBFFRRL').
code('FBFBFBBLLL').
code('FFFFBBBRLR').
code('FBBFBBBLRL').
code('BFBBFBBRRR').
code('FFFBFBFLRR').
code('BBBBFFBRRL').
code('FFBBFBFLLR').
code('FFFBFBBRLR').
code('BBFFFBFLRL').
code('FFBBBFBRRL').
code('FFBFBBBRRR').
code('BFBBBBFLLR').
code('BBFBBBFLRL').
code('BFBBFBBLLR').
code('BBFFFBBLRR').
code('FFBBFFBLRL').
code('BBBFFFFRRL').
code('BFFFBFFRLL').
code('BBBBFFFLRR').
code('FFBBBBFLRR').
code('FBBFFBFLRR').
code('BBBFFFFLLR').
code('BFFBFFFRRL').
code('FBFBFBBLRL').
code('BFBFFBFLLR').
code('BFFBFBFLLR').
code('BFBFFFBRRR').
code('FFBBFFFRRL').
code('BBFBBFBLLL').
code('FBBBFBFRLL').
code('BBFBBBFLRR').
code('BBBFFFBLRR').
code('BBFFFFBLLR').
code('FBBFBFFRLR').
code('FBFBFFBLLL').
code('BFFBBBFRLR').
code('BFFFFBBRRL').
code('BBBFFBFLLL').
code('FFFBFBFRRR').
code('FBFFBFFLRL').
code('FFBBBBBLLR').
code('BFFBBFBRRR').
code('FBBBBFBLRL').
code('BFBFBBBRLR').
code('BBFBBFFLLL').
code('BFFFFFBLRL').
code('FBBFBFBRRL').
code('FBBBFFFLLL').
code('BFFFBFBRRR').
code('FFBFBFFLRL').
code('FFBFBFBRRL').
code('FFBBBBBRRR').
code('FFFFBFBRLR').
code('BFBBFFBLLL').
code('BFFBBBFLLR').
code('FBBBFFBRLL').
code('FBFFBBBLRL').
code('BFFBBBBRRR').
code('FFBFFBBRRL').
code('BFBFFBBRLL').
code('FFFFFBFLRL').
code('FFBBBBFRRR').
code('FFBFFFFLLR').
code('BBBFBBBRRL').
code('FFFFFBBRLL').
code('FBFBBBBRRL').
code('FBBBFBFLRR').
code('FFFBBFFLRR').
code('FBFFFBFLRL').
code('FFBFFBFRLL').
code('FFFBFFFRRL').
code('FFFFBFBRLL').
code('BBFBFBBRLL').
code('FFBBBBFLLR').
code('FBFFFBBRRL').
code('BFBBBBBLLL').
code('BFBFFBBLLL').
code('FFFFBFBRRL').
code('FFBBFFBLRR').
code('BFBBFFFRRR').
code('FFBFFBFRLR').
code('BBFBBBBLRL').
code('FBBFBBBLLR').
code('BFFFBBFLLL').
code('FFFFBFFLLR').
code('BFFFFBFRLR').
code('FBBFBFBLRR').
code('BBBFFFFLRL').
code('BBFFFBBLRL').
code('BBFBFFBRLL').
code('FBBBBFBLLR').
code('FBFFBBFRLL').
code('BBFFBFBLLL').
code('FBBFFFBRLL').
code('BBBFBFBRRL').
code('FBFBBFBRLR').
code('BFBBBBFLLL').
code('FBFBFBFRLL').
code('FBFBBBFLLR').
code('BBFBFBFLLL').
code('BBFFFBFLLL').
code('BBBFFFBLLL').
code('BFBBBFBLLL').
code('FFBBBFFLLL').
code('FFBFFFFRRL').
code('FBBBBBFLLR').
code('FBBFFBBLRR').
code('BBFFFFFRLL').
code('FFFFFBBLRR').
code('BFBBFFBLRL').
code('BFFFFFBRRL').
code('BFBBFFFLLR').
code('FFFBFBBRRL').
code('FFBFFBBLRL').
code('BFFFFBBLRL').
code('FBFBBBBLRL').
code('FBBBFFBRRR').
code('FFBBFBBRLR').
code('BFBBFFBLRR').
code('FBBBFFBLRR').
code('FBFBFFBRLL').
code('FBFBFBFLLR').
code('BBFFFBBRRL').
code('BBBFBFBRLL').
code('BBFBBFFRRR').
code('BFBBFFFLRL').
code('BFBFBFFRRL').
code('BBFBBFFLRL').
code('BBFBFBFLRR').
code('BBFBFFFRRR').
code('BBBFFBFRLR').
code('BFFBBFFLRL').
code('FBBBBBBRLL').
code('BBFFFBBLLL').
code('FFFBBBBLLL').
code('BBFFFFBLRL').
code('FFBBFFBRLR').
code('BFBBBBBLRR').
code('BBFBBFBRRR').
code('FFFFFFBRLR').
code('FFFFBBFRLL').
code('FFFFBBFRLR').
code('FBFBBFFRRR').
code('FFFFBFBRRR').
code('FBFBFBBRRR').
code('FFFFFBBRRR').
code('BFBBBBBLRL').
code('BBBFBBFLLR').
code('BFBFFBBRRL').
code('BBBFFFBRLL').
code('BBFBBBBRRR').
code('FBFBBBFRRL').
code('BFBBFBFLLL').
code('FFFBBFBLLL').
code('BBFFBFBRRL').
code('FFBFFBBLLR').
code('FFBFBBFLLR').
code('BBBFBBFRLL').
code('FBBFFFFRRL').
code('FBBFFBFRRR').
code('BFFBFFBLLL').
code('FBFBFFBLRL').
code('BBBFBBFRLR').
code('FFBFBBBRRL').
code('FFBBBBFLLL').
code('FBFBBBFLRR').
code('FFBBFBFLRR').
code('FBFFBBFRRL').
code('FFBBFFFLLR').
code('FBFBFBBLRR').
code('BBBFBBBRLR').
code('BFFBFFFLLR').
code('BFFFBFBRRL').
code('FFBBBFBRRR').
code('BFFBFFFRRR').
code('BBBFBFFLRR').
code('FFFFFFBLRR').
code('BFBFBBFRRL').
code('FBFBBFBRLL').
code('FBBBBFFLLR').
code('BFBBBBFLRL').
code('FBBBBFBLLL').
code('FFBBFFBLLR').
code('BBBFFBBRRR').
code('BFBFFFFRRL').
code('FFBFFBBRRR').
code('BFFBBFFRRR').
code('FBFFBFFLLR').
code('BBFFFFFLLL').
code('BBBBFFBLRL').
code('BFBBBBFRRL').
code('FBBFBFFLLL').
code('FFFFFBFRLL').
code('FBBBBBFRRR').
code('BBBFBFFRLL').
code('BFBBBFFRLL').
code('FFBBBFFLRR').
code('BBFFFBFLRR').
code('BBFFFBFRRL').
code('BBFBFFBRLR').
code('FFBFFFBLRR').
code('FBFBFBBRRL').
code('FFFBBFFRRR').
code('FBBBBBBLLR').
code('FBBFFBBLLL').
code('FBBBBFFRRL').
code('BFBFFFFLRL').
code('BFBBBFBLLR').
code('FFFBFFBRLL').
code('FBFBBFBLRR').
code('FFBBFBBLRR').
code('BBBFBBBLRR').
code('BBFBBBFLLR').
code('BFBFBBBLRR').
code('BFBFBBFLRL').
code('FFFBBBBRRR').
code('BFBFFBBRRR').
code('FBBBBFFRRR').
code('FFFBBFBRLR').
code('FBFFFBFRLL').
code('BFBFFBBLRL').
code('FFBFBBFRRL').
code('BFFFFFFLLL').
code('BFBFFFFLLL').
code('BBFFBFFRRL').
code('BFFBBFFRLR').
code('FFFBFFBLLL').
code('BBFBFFBLLL').
code('FBFFBBBRLR').
code('FBBBBFFLRL').
code('FBFFBBBRRR').
code('BFFBBFBLLL').
code('BFBFBFBLLR').
code('FBFFFFBRLR').
code('BBFFFBBRRR').
code('BFBBFFBLLR').
code('FFFBFBBRLL').
code('BBFFFFBRRR').
code('BFFBBFBLRR').
code('FBFBFBFRLR').
code('FBFFFBFLRR').
code('FFBBBBBRRL').
code('FBFFBBBRRL').
code('BBBFFFBRRR').
code('FBFFFFBLLR').
code('BBFBFBFRRL').
code('BBFBFFFRLR').
code('BFFFFBFLRL').
code('BBBBFFFRRL').
code('FBBFBBFRLL').
code('BFBFBFBLLL').
code('FBBBBBBLRR').
code('FFBBBBBLRR').
code('BFFBBFFRLL').
code('FFFFBBFLLR').
code('FFBBFFBLLL').
code('FFBFBBFRLL').
code('BBBFBFBRRR').
code('BFBBFBFRLR').
code('FFBBFFFRLL').
code('FBFFFBFLLL').
code('FFBFFBBLRR').
code('BFBFBBFLRR').
code('FBBFFBFRLR').
code('BBBFBFBLRR').
code('BBFFBBBLLL').
code('FFFBBBFRRR').
code('BFFBBBBLLL').
code('FFFBBFBLLR').
code('BFBBBBFRLR').
code('FBFFBFBRLL').
code('FFBFFBFLRR').
code('FFFBFFBRLR').
code('BFBFFBFRLR').
code('BFBBBFFLRR').
code('BFBBFBFLLR').
code('BBFBBFBRRL').
code('FBFBFFBRRR').
code('BFBBFFBRRR').
code('BBFBFFBLRR').
code('FBFFFFBRRL').
code('FFFBBBBRLL').
code('FFBBFFFLLL').
code('BFBFBBFLLR').
code('FBBBFBBLLL').
code('BBFFBBFLRR').
code('FBFFFFFRRL').
code('BFBFFBBLLR').
code('FBBFFBBLLR').
code('BBBFBFBRLR').
code('BFFFFFFLRR').
code('BBFFBFBRLR').
code('FBBFFBBRRL').
code('BFFFFBBLLR').
code('BBFBBFBRLR').
code('FFBBBBFRRL').
code('BFFBBBBLLR').
code('FFBBFBBLRL').
code('BFBFFFFRLL').
code('BFFFBBFRLL').
code('BFBFBBFRLR').
code('BBFFBBFLLL').
code('FFBBBFBLRR').
code('FBFFBBBLLL').
code('FFBFFFBLLL').
code('FBBFFFBLLL').
code('FFBBBBBLRL').
code('FBBFFBFRLL').
code('FFFBBBFLLR').
code('BBBFBBBLRL').
code('BFFBFFBLLR').
code('BFBFBBBLRL').
code('FFBFFFBRLR').
code('BBBFFBFRRR').
code('BFFBFBFRLR').
code('FFBBBBFLRL').
code('FBBFBBFLRR').
code('FBBBFFFRRR').
code('FBFBFFFRRR').
code('FFFBFFFRLR').
code('BFBBFBFLRR').
code('FFBFFBBLLL').
code('FFBFFFFLLL').
code('FBFFBFBLLL').
code('BFBFFFBLRR').
code('FBFFFFFRLR').
code('BBFBFBBLRL').
code('FFBFBFBRRR').
code('FFBFFFBLRL').
code('FFBBFBBRRR').
code('BBFFBFBRLL').
code('FFFBFBFRRL').
code('FFBFFFBLLR').
code('FFFBFFFRLL').
code('FFBFBFBLLL').
code('FFFBFFBRRR').
code('BBBFFBFRLL').
code('FFBFBFFLLR').
code('BBBFFBFLRL').
code('FBFBBBBLLR').
code('FBBFBFBLLR').
code('FFBBFBBLLL').
code('BFFBFFFLRR').
code('BBFFBBBLRR').
code('FBBFBBBRLL').
code('FBFBBBFRLR').
code('BFFFBBBRRL').
code('BFBBFFBRLR').
code('FBBBFFFRRL').
code('BFBFFBFLLL').
code('FBBBFBBLRL').
code('FBFBBBBLLL').
code('FBFFBFBLLR').
code('FFBBFBFRRL').
code('BFFBBBBRLL').
code('BBBFFBBLLR').
code('BBFBFFBRRL').
code('FFFFFFBLLL').
code('BFBBBFBRLR').
code('BFFFBFFLLL').
